;;; init-activity-tests.el --- Activity lifecycle regressions -*- lexical-binding: t -*-

(require 'ert)
(require 'compile)
(require 'comp-run)
(require 'init-activity-noema)

(defvar my/noema--ready nil)
(defvar my/noema--process nil)
(defvar remote-tasks nil)
(defvar features nil)

(defmacro my/activity-test-isolated (&rest body)
  "Run BODY without starting Noema or retaining indicator timers."
  (declare (indent 0))
  `(let ((my/activity-indicator-mode nil)
         (my/activity--registered nil)
         (my/activity--timer nil)
         (my/activity--count 0)
         (my/activity--frame-index 0)
         (my/activity--last-poll 0)
         (my/activity-poll-functions nil)
         (my/activity-noema--agents (make-hash-table :test #'eq))
         (my/activity-noema--tasks nil)
         (my/activity-noema--pending nil)
         (compilation-in-progress nil)
         (comp-async-compilations nil)
         (comp-files-queue nil)
         (remote-tasks nil)
         (my/noema--ready nil)
         (my/noema--process nil))
     (unwind-protect (progn ,@body)
       (when (timerp my/activity--timer)
         (cancel-timer my/activity--timer)))))

(ert-deftest my/activity-row-keys-work-including-unbound-help ()
  (my/activity-test-isolated
    (with-temp-buffer
      (my/activity-board-mode)
      (let ((inhibit-read-only t))
        (aaron-ui-board-insert-row :id "process" :title "Process"
                                   :detail "Command" :action #'ignore))
      (goto-char (point-min))
      (should buffer-read-only)
      (should (eq (key-binding "j") #'next-line))
      (should (eq (key-binding "k") #'previous-line))
      (should (eq (key-binding "x") #'my/activity-board-stop))
      (should (eq (key-binding "z") #'my/activity-board-help))
      (let ((inhibit-read-only nil))
        (call-interactively (key-binding "j"))
        (call-interactively (key-binding "z")))
      (should (= (line-number-at-pos) 2)))))

(ert-deftest my/activity-registration-cleans-up-on-return-and-error ()
  (my/activity-test-isolated
    (should (= 42 (my/with-activity "work"
                    (should (= 1 (my/activity-count))) 42)))
    (should (= 0 (my/activity-count)))
    (should-error (my/with-activity "failed work" (error "failed")))
    (should-not my/activity--registered)
    (should (= 0 my/activity--count))))

(ert-deftest my/activity-animation-advances-and-returns-to-rest ()
  (my/activity-test-isolated
    (let ((my/activity-indicator-mode t)
          (my/activity-indicator-fps 20))
      (let* ((handle (my/activity-register "animation probe"))
             (initial my/activity--frame-index))
        (should (timerp my/activity--timer))
        (sleep-for 0.18)
        (should (> my/activity--frame-index initial))
        (should (= 1 my/activity--count))
        (my/activity-unregister handle)
        (sleep-for 0.18)
        (should (= 0 my/activity--count))
        ;; A rest glyph ignores the former frame number immediately.
        (should (equal (substring-no-properties (my/activity-mode-line-text))
                       " ᕕ( ᴗ )ᕗ"))))))

(ert-deftest my/activity-empty-task-snapshot-does-not-rescan-per-process ()
  (my/activity-test-isolated
    (let ((process (make-pipe-process :name "activity-service" :noquery t))
          (scans 0))
      (unwind-protect
          (cl-letf (((symbol-function 'my/activity--owned-task-processes)
                     (lambda () (cl-incf scans) nil)))
            (dotimes (_ 10)
              (should (eq (my/activity-process-kind process nil) 'service)))
            (should (= scans 0))
            (should (eq (my/activity-process-kind process) 'service))
            (should (= scans 1)))
        (delete-process process)))))

(ert-deftest my/activity-noema-counts-busy-agents-without-idle-or-export-duplicates ()
  (my/activity-test-isolated
    (let ((features (cons 'noema-agent-acp features))
          (worker (generate-new-buffer " *activity-worker*"))
          (export (generate-new-buffer " *activity-export*"))
          (idle (generate-new-buffer " *activity-idle*"))
          (busy t)
          (stops nil))
      (unwind-protect
          (cl-letf (((symbol-function 'noema-agent-acp-sessions)
                     (lambda (&optional _)
                       (list (list :buffer worker :name "codex/work" :busy busy)
                             (list :buffer export :origin 'latex-export :busy t)
                             (list :buffer idle :busy nil))))
                    ((symbol-function 'noema-agent-acp-stop)
                     (lambda (buffer) (push buffer stops))))
            (my/activity-noema--update-agents)
            (should (= 1 (my/activity-count)))
            (let* ((activity (gethash worker my/activity-noema--agents))
                   (since (my/activity-started-at activity)))
              (funcall (my/activity-cancel activity))
              (should (equal stops (list worker)))
              (my/activity-noema--update-agents)
              (should (= since (my/activity-started-at
                                (gethash worker my/activity-noema--agents)))))
            (setq busy nil)
            (my/activity-noema--update-agents)
            (should (= 0 (my/activity-count))))
        (mapc #'kill-buffer (list worker export idle))))))

(ert-deftest my/activity-noema-polls-asynchronously-and-filters-terminal-tasks ()
  (my/activity-test-isolated
    (let ((my/noema--ready t)
          (my/noema--process 'host)
          (calls 0) callback channel arguments)
      (cl-letf (((symbol-function 'my/noema-api-call)
                 (lambda (method args cb &optional _timeout)
                   (cl-incf calls)
                   (setq channel method arguments args callback cb))))
        (my/activity-noema--poll)
        (my/activity-noema--poll)
        (should (= calls 1))
        (should (equal channel "aaronnote:api:tasks:list"))
        (should (equal arguments [((activeOnly . t))]))
        (funcall callback
                 '((tasks . [((id . "latex") (title . "Export note")
                               (kind . "latex-export") (status . "running")
                               (phase . "Compiling") (cancellable . t))
                              ((id . "done") (status . "completed"))])) nil)
        (should-not my/activity-noema--pending)
        (should (= 1 (my/activity-count)))
        (should (string-match-p "Compiling"
                                (my/activity-detail (car my/activity-noema--tasks))))
        (funcall (my/activity-cancel (car my/activity-noema--tasks)))
        (should (equal channel "aaronnote:api:tasks:cancel"))
        (should (equal arguments [((id . "latex"))]))
        (funcall callback '((ok . t)) nil)
        (should (equal channel "aaronnote:api:tasks:list"))
        (funcall callback '((tasks . [])) nil)
        (should (= 0 (my/activity-count)))))))

(ert-deftest my/activity-noema-host-stop-and-disable-ignore-stale-replies ()
  (my/activity-test-isolated
    (let ((my/noema--ready t)
          (my/noema--process 'old-host)
          callback)
      (cl-letf (((symbol-function 'my/noema-api-call)
                 (lambda (_method _args cb &optional _timeout) (setq callback cb))))
        (my/activity-noema--poll)
        (let ((old callback))
          (setq my/noema--ready nil)
          (my/activity-noema--host-stopped)
          (setq my/noema--ready t my/noema--process 'new-host)
          (my/activity-noema--poll)
          (funcall old '((tasks . [((id . "stale") (status . "running"))])) nil)
          (should my/activity-noema--pending)
          (should-not my/activity-noema--tasks))
        (my/activity-noema--mode-changed)
        (funcall callback '((tasks . [((id . "disabled") (status . "running"))])) nil)
        (should-not my/activity-noema--tasks)))))

(ert-deftest my/activity-noema-offline-poll-does-not-call-or-start-host ()
  (my/activity-test-isolated
    (cl-letf (((symbol-function 'my/noema-api-call)
               (lambda (&rest _) (ert-fail "Offline poll called the host"))))
      (my/activity-noema--poll)
      (should (= 0 (my/activity-count))))))

(ert-deftest my/activity-noema-unchanged-agent-snapshot-does-not-redraw-board ()
  (my/activity-test-isolated
    (let ((features (cons 'noema-agent-acp features))
          (worker (generate-new-buffer " *activity-stable-worker*"))
          (changes 0))
      (unwind-protect
          (cl-letf (((symbol-function 'noema-agent-acp-sessions)
                     (lambda (&optional _)
                       (list (list :buffer worker :name "work" :busy t))))
                    ((symbol-function 'my/activity-noema--changed)
                     (lambda () (cl-incf changes))))
            (my/activity-noema--update-agents)
            (dotimes (_ 5) (my/activity-noema--update-agents))
            (should (= 1 changes)))
        (kill-buffer worker)))))

(ert-deftest my/activity-noema-failed-request-releases-pending-and-can-recover ()
  (my/activity-test-isolated
    (let ((my/noema--ready t)
          (my/noema--process 'host)
          (calls 0) callback)
      (cl-letf (((symbol-function 'my/noema-api-call)
                 (lambda (_method _args cb &optional _timeout)
                   (cl-incf calls) (setq callback cb))))
        (my/activity-noema--poll)
        (funcall callback nil '((message . "timeout")))
        (should-not my/activity-noema--pending)
        (my/activity-noema--poll)
        (should (= 2 calls))
        (funcall callback '((tasks . [((id . "recovered") (status . "running"))])) nil)
        (should (= 1 (my/activity-count)))))))

(ert-deftest my/activity-providers-poll-at-idle-rate-during-animation ()
  (my/activity-test-isolated
    (let* ((calls 0)
          (my/activity-poll-functions (list (lambda () (cl-incf calls))))
          (my/activity--last-poll 10)
          (my/activity-poll-interval 2)
          (now 10.5))
      (cl-letf (((symbol-function 'float-time) (lambda (&rest _) now)))
        (dotimes (_ 8) (my/activity--poll))
        (should (= calls 0))
        (setq now 12.0)
        (my/activity--poll)
        (should (= calls 1))
        (dotimes (_ 8) (my/activity--poll))
        (should (= calls 1))))))

(provide 'init-activity-tests)
;;; init-activity-tests.el ends here
