;;; init-jupyter-command-tests.el -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'init-jupyter-command)

(defconst my/jupyter-command-test-context
  (remote-context-create :target-id "test-remote" :localname "/project/a.ipynb"
                         :workspace-root "/fs:test-remote:/project/"))

(ert-deftest my/jupyter-command-uses-target-project-environment-before-path ()
  (cl-letf (((symbol-function 'remote-executable-find)
             (lambda (program context)
               (should (equal (remote-context-target-id context) "test-remote"))
               (pcase program
                 ("/project/.conda/bin/jupyter" program)
                 ("jupyter" "/system/bin/jupyter")))))
    (should (equal (my/jupyter-target-command my/jupyter-command-test-context)
                   '("/project/.conda/bin/jupyter")))))

(ert-deftest my/jupyter-command-reuses-conda-registry-without-client-home ()
  (cl-letf (((symbol-function 'remote-executable-find)
             (lambda (program _context)
               (and (equal program "/remote/conda/bin/jupyter") program)))
            ((symbol-function 'file-readable-p)
             (lambda (path)
               (should (equal path "/fs:test-remote:/home/user/.conda/environments.txt")) t))
            ((symbol-function 'remote-expand-file-name)
             (lambda (path _directory context)
               (should (equal path "~/.conda/environments.txt"))
               (should (equal (remote-context-target-id context) "test-remote"))
               "/fs:test-remote:/home/user/.conda/environments.txt"))
            ((symbol-function 'insert-file-contents)
             (lambda (_path &rest _) (insert "/remote/conda\n"))))
    (should (equal (my/jupyter-target-command my/jupyter-command-test-context)
                   '("/remote/conda/bin/jupyter")))))

(ert-deftest my/jupyter-command-supports-target-python-module-without-cli ()
  (cl-letf (((symbol-function 'remote-executable-find)
             (lambda (program _context) (and (equal program "python3") "/target/bin/python3")))
            ((symbol-function 'file-readable-p) (lambda (_) nil))
            ((symbol-function 'remote-expand-file-name) (lambda (&rest _) "/fs:test-remote:/home/user/.conda/environments.txt"))
            ((symbol-function 'process-file)
             (lambda (program &rest _)
               (should (equal program "/target/bin/python3"))
               (should (equal default-directory "/fs:test-remote:/project/")) 0)))
    (should (equal (my/jupyter-target-command my/jupyter-command-test-context)
                   '("/target/bin/python3" "-m" "jupyter")))))

(ert-deftest my/jupyter-command-missing-installation-is-actionable ()
  (cl-letf (((symbol-function 'remote-executable-find) (lambda (&rest _) nil))
            ((symbol-function 'file-readable-p) (lambda (_) nil))
            ((symbol-function 'remote-expand-file-name) (lambda (&rest _) "/fs:test-remote:/home/user/.conda/environments.txt")))
    (let ((err (should-error (my/jupyter-target-command my/jupyter-command-test-context)
                             :type 'user-error)))
      (should (string-match-p "test-remote.*project.*jupyter_client" (error-message-string err))))))

(ert-deftest my/jupyter-command-does-not-replace-explicit-configuration ()
  (cl-letf (((symbol-function 'remote-executable-find)
             (lambda (program _context)
               (should (equal program "/configured/jupyter")) nil)))
    (should-error (my/jupyter-target-command my/jupyter-command-test-context "/configured/jupyter")
                  :type 'user-error)))
