;;; init-aaronnote-agenda-source-tests.el --- Gateway source tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'init-aaronnote)
(require 'init-aaronnote-agenda-source)
(require 'noema-agenda)

(ert-deftest my/noema-attention-navigation-waits-for-entry-and-resolves-the-exact-task ()
  (let ((noema-agenda--project-root nil) (noema-agenda--project-scope nil)
        (noema-agenda--project-lease nil) (noema-agenda--project-request 0)
        (noema-agenda--project-callbacks nil) (noema-agenda-project-root-function #'identity)
        (my/noema--attention-visit-request 0) (my/project-active-root nil)
        entry query visited operations)
    (cl-letf (((symbol-function 'my/project-activate)
               (lambda (root &optional remember)
                 (should remember) (setq my/project-active-root root)
                 (noema-agenda-activate-project root)))
              ((symbol-function 'noema-agenda--update-scopes) #'ignore)
              ((symbol-function 'noema-agenda-visit-record) (lambda (record) (setq visited record)))
              ((symbol-function 'noema-agenda--call)
               (lambda (operation body callback)
                 (push operation operations)
                 (pcase operation
                   ("enter" (setq entry callback))
                   ("query" (should (equal (alist-get 'scopes body) ["scope"])) (setq query callback))))))
      (my/noema--agenda-attention-visit '((root . "/project") (file . "/project/tasks.md") (uid . "exact")))
      (should (equal operations '("enter"))) (should-not query) (should-not visited)
      (funcall entry '((id . "scope")) nil)
      (should (equal operations '("query" "enter")))
      (funcall query '((todos . [((uid . "exact-prefix") (file . "/project/tasks.md") (source . "wrong"))
                                ((uid . "exact") (file . "/project/tasks.md") (source . "@@todo [Correct]{id: exact}"))])) nil)
      (should (equal (alist-get 'source visited) "@@todo [Correct]{id: exact}"))
      (setq visited nil)
      (noema-agenda-activate-project nil)
      (noema-agenda-activate-project "/project")
      (funcall entry '((id . "scope")) nil)
      (funcall query '((todos . [((uid . "exact") (file . "/project/tasks.md") (source . "stale"))])) nil)
      (should-not visited))))

(ert-deftest my/noema-source-gateway-protects-buffers-and-client-leases ()
  (let* ((root (make-temp-file "agenda-gateway-source-" t))
         (logical (remote-make-file-name "local" root))
         (client (list 'source-test-client))
         (my/noema--agenda-source-handles (make-hash-table :test #'equal))
         result done)
    (cl-labels ((request (body)
                  (setq result nil done nil)
                  (my/noema--agenda-source-request (cons '(lease . "test-lease") body) client)
                  (let ((deadline (+ (float-time) 10)))
                    (while (and (not done) (< (float-time) deadline)) (accept-process-output nil 0.02)))
                  (should done)
                  result))
      (cl-letf (((symbol-function 'remote-gateway-defer) (lambda (&rest _) 'deferred))
                ((symbol-function 'remote-gateway-resolve) (lambda (_ value) (setq result value done t)))
                ((symbol-function 'remote-gateway-notify) #'ignore))
        (unwind-protect
            (progn
              (should-not (alist-get 'error (request `((op . "open") (root . ,logical)
                                                      (options . ((hidden . :json-false) (extensions . [".md"])))))))
              (should-not (alist-get 'error (request '((op . "write") (path . "test.md") (content . "original") (expectedRevision . nil)))))
              (let* ((snapshot (request '((op . "read") (path . "test.md")))))
                (should (equal (alist-get 'content snapshot) "original"))
                (with-temp-buffer
                  (setq buffer-file-name (expand-file-name "test.md" root))
                  (insert "unsaved")
                  (should (equal (alist-get 'code (alist-get 'error (request `((op . "write") (path . "test.md")
                                                                                             (content . "overwrite") (expectedRevision . ,(alist-get 'revision snapshot))))))
                                 "EBUSY"))))
              (should-error (my/noema--agenda-source-request '((lease . "test-lease") (op . "list")) '(other-client)))
              (should (equal (alist-get 'files (request '((op . "list")))) '("test.md")))
              (my/noema--agenda-source-release-client client)
              (should (= (hash-table-count my/noema--agenda-source-handles) 0))
              (should-error (my/noema--agenda-source-request '((lease . "test-lease") (op . "read") (path . "test.md")) client)))
          (my/noema--agenda-source-release-client client)
          (delete-directory root t))))))

(provide 'init-aaronnote-agenda-source-tests)
