;;; init-aaronnote-agenda-apple-tests.el --- Client helper lifecycle -*- lexical-binding: t; -*-
(require 'ert)
(require 'init-aaronnote-agenda-apple)

(ert-deftest my/noema-apple-status-uses-owned-client-process-without-authorizing ()
  (unwind-protect
      (progn
        (my/noema--apple-start)
        (should (memq my/noema--apple-resource (remote-workspace-resources my/noema--apple-workspace)))
        (let (done result problem)
          (my/noema--apple-request '((op . "status"))
                                   (lambda (value error-object) (setq done t result value problem error-object)))
          (let ((deadline (+ (float-time) 10)))
            (while (and (not done) (< (float-time) deadline)) (accept-process-output nil 0.02)))
          (should done) (should-not problem)
          (should (= (alist-get 'protocol result) 1)))
        (should-error (my/noema--apple-gateway '((op . "authorize") (kind . "reminder")) '(test-client)))
        (let ((process my/noema--apple-process))
          (my/noema--apple-stop)
          (should-not (process-live-p process)))
        (should (= (hash-table-count my/noema--apple-pending) 0))
        (let (problem)
          (my/noema--apple-request '((op . "status")) (lambda (_ error-object) (setq problem error-object)))
          (should (equal (alist-get 'code problem) "EDISABLED"))))
    (my/noema--apple-stop)))

(ert-deftest my/noema-apple-recovery-releases-pending-and-preserves-client-subscription ()
  (let ((client '(apple-test-client)) notifications)
    (unwind-protect
        (cl-letf (((symbol-function 'remote-gateway-notify)
                   (lambda (recipient _method event)
                     (when (eq recipient client) (push event notifications)))))
          (puthash client t my/noema--apple-clients)
          (my/noema--apple-start)
          (should (gethash client my/noema--apple-clients))
          (let* ((generation my/noema--apple-generation)
                 (process my/noema--apple-process)
                 (timer (run-at-time 60 nil #'ignore))
                 failures)
            (puthash 900 (cons (lambda (_ error-object) (push error-object failures)) timer)
                     my/noema--apple-pending)
            (remote-workspace-recover-resource my/noema--apple-workspace my/noema--apple-resource)
            (should-not (process-live-p process))
            (should (= (length failures) 1))
            (should-not (memq timer timer-list))
            (my/noema--apple-filter generation process "{\"id\":900,\"result\":{}}\n")
            (should (= (length failures) 1))
            (let (done problem)
              (my/noema--apple-request '((op . "status"))
                                       (lambda (_ error-object) (setq done t problem error-object)))
              (let ((deadline (+ (float-time) 10)))
                (while (and (not done) (< (float-time) deadline)) (accept-process-output nil 0.02)))
              (should done) (should-not problem))
            (should (seq-find (lambda (event) (equal (alist-get 'event event) "ready")) notifications))
            (my/noema--apple-stop)
            (should (gethash client my/noema--apple-clients))
            (my/noema--apple-client-left client)
            (should-not (gethash client my/noema--apple-clients))))
      (my/noema--apple-client-left client)
      (my/noema--apple-stop))))

(provide 'init-aaronnote-agenda-apple-tests)
