;;; jupyter-debug-live-smoke.el --- Real kernel, Noema and Dape debugging -*- lexical-binding: t; -*-
(require 'init-aaronnote-jupyter-debug)
(require 'dape)

(defun my/jupyter-debug-live--wait (predicate label)
  (let ((deadline (+ (float-time) 30)))
    (while (and (not (funcall predicate)) (< (float-time) deadline))
      (accept-process-output nil .03))
    (unless (funcall predicate) (error "Timed out: %s" label))))

(defun my/jupyter-debug-live--request (conn command arguments)
  (let (settled reply failure)
    (dape-request conn command arguments
                  (lambda (body error) (setq reply body failure error settled t)))
    (my/jupyter-debug-live--wait (lambda () settled) (format "%s" command))
    (when failure (error "DAP %s: %s" command failure))
    reply))

(defun my/jupyter-debug-live--scenario (file)
  (let* ((origin (current-buffer))
         (cell (car (my/noema-jupyter-notebook-projection-cells)))
         (start (plist-get cell :body-beg))
         (line (plist-get cell :line))
         (dape-start-hook nil)
         (dape-stopped-hook nil))
    (delete-region start (plist-get cell :body-end))
    (goto-char start)
    (insert "audit_value = 10\naudit_value += 2\nprint(audit_value)")
    (save-buffer)
    (goto-char start)
    (forward-line 1)
    (dape-breakpoint-toggle)
    (message "Debug live: starting breakpoint session")
    (my/noema-jupyter-debug-start)
    (let ((conn (car dape--connections)))
      (my/jupyter-debug-live--wait
       (lambda () (equal (plist-get (dape--current-stack-frame conn) :line) (1+ line)))
       "notebook breakpoint")
      (let* ((frame (dape--current-stack-frame conn))
             (scopes (my/jupyter-debug-live--request conn :scopes `(:frameId ,(plist-get frame :id))))
             (reference (plist-get (aref (plist-get scopes :scopes) 0) :variablesReference))
             (variables (my/jupyter-debug-live--request conn :variables `(:variablesReference ,reference))))
        (unless (equal (plist-get (plist-get frame :source) :path) file)
          (error "Stack frame did not map to the notebook"))
        (unless (cl-find-if (lambda (item) (and (equal (plist-get item :name) "audit_value")
                                               (equal (plist-get item :value) "10")))
                            (append (plist-get variables :variables) nil))
          (error "Paused-frame variables are wrong")))
      (dape-next conn)
      (my/jupyter-debug-live--wait
       (lambda () (equal (plist-get (dape--current-stack-frame conn) :line) (+ 2 line)))
       "next statement")
      (let ((value (my/jupyter-debug-live--request conn :evaluate '(:expression "audit_value" :context "repl"))))
        (unless (equal (plist-get value :result) "12") (error "Step/evaluate failed: %S" value)))
      (dape-continue conn)
      (my/jupyter-debug-live--wait
       (lambda () (not (buffer-local-value 'my/noema-jupyter-debug--id origin))) "debug completion"))
    (with-current-buffer origin
      (unless (not buffer-read-only) (error "Debugger left notebook read-only"))
      (dape-breakpoint-remove-all)
      (goto-char start)
      (message "Debug live: starting Run by Line")
      (my/noema-jupyter-run-by-line)
      (let ((conn (car dape--connections)))
        (my/jupyter-debug-live--wait
         (lambda () (equal (plist-get (dape--current-stack-frame conn) :line) line)) "entry stop")
        (with-current-buffer origin (my/noema-jupyter-run-by-line))
        (my/jupyter-debug-live--wait
         (lambda () (equal (plist-get (dape--current-stack-frame conn) :line) (1+ line))) "Run by Line next")
        (with-current-buffer origin (my/noema-jupyter-debug-continue))
        (my/jupyter-debug-live--wait
         (lambda () (not (buffer-local-value 'my/noema-jupyter-debug--id origin))) "Run by Line completion"))
      (let ((raw (my/noema-jupyter-notebook--read-raw file)))
        (unless (string-match-p "12" (prin1-to-string (gethash "outputs" (aref (gethash "cells" raw) 0))))
          (error "Debugger execution output was not persisted"))))
    (princ "PASS real Dape breakpoint, notebook source map, scopes/variables, next/evaluate, Run by Line, persisted output\n")))

(let ((my/jupyter-contents-live-extra #'my/jupyter-debug-live--scenario))
  (load (expand-file-name "test/jupyter-contents-live-smoke.el" user-emacs-directory) nil t))
