;;; popup-agent-tests.el --- Shared terminal/ACP popup regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'init-vterm-popup)
(require 'noema-agent-acp)
(require 'init-ai-ide)

(ert-deftest agent-shell-close-does-not-prompt-for-txt-or-disable-other-queries ()
  (dolist (popup '(nil t))
    (let ((buffer (generate-new-buffer " *popup-transcript-test*"))
          (shell-maker-prompt-before-killing-buffer t)
          (queries 0))
      (unwind-protect
          (with-current-buffer buffer
            (setq major-mode 'agent-shell-mode)
            (setq-local shell-maker--config 'test
                        kill-buffer-query-functions
                        (list #'shell-maker-kill-buffer-query
                              (lambda () (cl-incf queries) t)))
            (insert "Agent output and an unsent prompt")
            (run-hooks 'agent-shell-mode-hook)
            (when popup (my/vterm-popup-apply-ui buffer))
            (should (buffer-modified-p))
            (should (local-variable-p 'shell-maker-prompt-before-killing-buffer))
            (should-not shell-maker-prompt-before-killing-buffer)
            (cl-letf (((symbol-function 'y-or-n-p) (lambda (&rest _) (ert-fail "Asked to save transcript")))
                      ((symbol-function 'shell-maker-save-session-transcript) (lambda () (ert-fail "Exported transcript"))))
              (should (kill-buffer buffer)))
            (should (= queries 1)))
        (when (buffer-live-p buffer)
          (with-current-buffer buffer (set-buffer-modified-p nil))
          (kill-buffer buffer))))))

(ert-deftest agent-shell-transcripts-disabled-for-new-and-existing-sessions ()
  (should-not (agent-shell--transcript-file-path))
  (with-temp-buffer
    (setq major-mode 'agent-shell-mode)
    ;; Existing sessions retain their old path until the policy is applied.
    (setq-local agent-shell--transcript-file "/unused/transcript.md")
    (my/agent-shell-disable-transcripts)
    (cl-letf (((symbol-function 'write-region)
               (lambda (&rest _) (ert-fail "Wrote a transcript")))
              ((symbol-function 'make-directory)
               (lambda (&rest _) (ert-fail "Created a transcript directory"))))
      (should-not (agent-shell--ensure-transcript-file))
      (agent-shell--append-transcript :text "Agent output"
                                      :file-path agent-shell--transcript-file))))

(ert-deftest popup-agent-transcript-policy-does-not-affect-other-buffers ()
  (let ((shell-maker-prompt-before-killing-buffer t))
    (with-temp-buffer
      (my/vterm-popup-apply-ui (current-buffer))
      (should shell-maker-prompt-before-killing-buffer)
      (should-not (local-variable-p 'shell-maker-prompt-before-killing-buffer)))
    (should shell-maker-prompt-before-killing-buffer)))

(ert-deftest agent-shell-opencode-prefers-verified-binary-without-changing-arguments ()
  (let ((agent-shell-opencode-acp-command '("opencode" "acp"))
        (my/agent-shell-opencode-executable "/test/official/opencode"))
    (cl-letf (((symbol-function 'file-executable-p) (lambda (path) (equal path "/test/official/opencode"))))
      (my/agent-shell-use-official-opencode)
      (should (equal agent-shell-opencode-acp-command '("/test/official/opencode" "acp"))))))

(ert-deftest agent-shell-opencode-preserves-custom-launchers-and-missing-install ()
  (let ((agent-shell-opencode-acp-command '("/custom/opencode" "acp" "--pure")))
    (cl-letf (((symbol-function 'file-executable-p) (lambda (_) (ert-fail "Custom launcher was inspected"))))
      (my/agent-shell-use-official-opencode)
      (should (equal agent-shell-opencode-acp-command '("/custom/opencode" "acp" "--pure")))))
  (let ((agent-shell-opencode-acp-command '("opencode" "acp")))
    (cl-letf (((symbol-function 'file-executable-p) (lambda (_) nil)))
      (my/agent-shell-use-official-opencode)
      (should (equal agent-shell-opencode-acp-command '("opencode" "acp"))))))

(ert-deftest agent-shell-opencode-expands-config-store-abbreviated-paths ()
  (let ((agent-shell-opencode-acp-command '("opencode" "acp"))
        (my/agent-shell-opencode-executable "~/.config/emacs/var/opencode"))
    (cl-letf (((symbol-function 'file-executable-p) (lambda (_) t)))
      (my/agent-shell-use-official-opencode)
      (should (equal (car agent-shell-opencode-acp-command)
                     (expand-file-name my/agent-shell-opencode-executable))))))

(ert-deftest agent-shell-native-entrypoint-projects-logical-cwd ()
  ;; Call upstream's public CWD directly, without the Noema start wrapper.
  (let ((agent-shell-cwd-function (lambda () "/fs:local:/Users/test/project/")))
    (cl-letf (((symbol-function 'remote-client-file-name)
               (lambda (path)
                 (should (equal path "/fs:local:/Users/test/project/"))
                 "/Users/test/project/")))
      (should (equal (agent-shell-cwd) "/Users/test/project/")))))

(ert-deftest agent-shell-native-directory-preserves-custom-native-cwd ()
  (cl-letf (((symbol-function 'remote-client-file-name)
             (lambda (_) (ert-fail "Native path requires no projection"))))
    (should (equal (my/agent-shell-native-directory "/Users/test/project/")
                   "/Users/test/project/"))))

(ert-deftest agent-shell-native-directory-fails-early-for-unavailable-target ()
  (cl-letf (((symbol-function 'remote-client-file-name) (lambda (_) nil)))
    (should-error (my/agent-shell-native-directory "/fs:server:/project/") :type 'user-error)))

(ert-deftest popup-agent-launchers-are-memory-only ()
  (cl-letf (((symbol-function 'executable-find) (lambda (&rest _) (ert-fail "Header checked executables")))
            ((symbol-function 'noema-agent-acp-start) (lambda (&rest _) (ert-fail "Header started agent"))))
    (let* ((term (my/vterm-popup--new-tab-segment))
           (agent (my/vterm-popup--agent-tab-segment))
           (term-map (get-text-property 0 'local-map term))
           (agent-map (get-text-property 0 'local-map agent)))
      (should (eq (lookup-key term-map [header-line mouse-3]) #'my/vterm-popup-menu))
      (should (eq (lookup-key agent-map [tab-line mouse-1]) #'my/vterm-popup-agent-menu))
      (should (equal (mapcar (lambda (item) (aref item 0)) (my/vterm-popup--agent-menu-items))
                     '("Claude" "Codex" "OpenCode"))))))

(ert-deftest popup-agent-menu-includes-configured-apps-and-agent-submenu ()
  (let ((my/project-popup-vterm-apps '(("yazi" . "yazi") ("btop" . "btop"))) items)
    (cl-letf (((symbol-function 'easy-menu-create-menu) (lambda (_title entries) (setq items entries)))
              ((symbol-function 'popup-menu) #'ignore))
      (my/vterm-popup-menu nil))
    (should (equal (mapcar (lambda (item) (aref item 0)) (cdr (assoc "Applications" items))) '("yazi" "btop")))
    (should (= (length (cdr (assoc "Agent" items))) 3))))

(ert-deftest popup-agent-starts-acp-not-vterm-and-shares-the-real-popup ()
  (save-window-excursion
    (let ((my/vterm-popup-buffers nil) (my/vterm-popup-current-buffer nil)
          (my/vterm-popup--displaying t) (my/vterm-popup-window-height 0.3)
          (agent (generate-new-buffer " *popup-test-agent*"))
          (term (generate-new-buffer " *popup-test-terminal*")) started)
      (unwind-protect
          (cl-letf (((symbol-function 'my/vterm-workspace-id) (lambda (&rest _) "local"))
                    ((symbol-function 'noema-agent-acp-config-for) (lambda (id) (list id)))
                    ((symbol-function 'noema-agent-acp-start)
                     (lambda (&rest args)
                       (setq started args)
                       (with-current-buffer agent
                         (setq major-mode 'agent-shell-mode)
                         (setq-local header-line-format "native ACP header")
                         (noema-agent-acp-tabs-mode 1))
                       agent))
                    ((symbol-function 'my/vterm-popup--create-buffer) (lambda (&rest _) (ert-fail "Agent used vterm")))
                    ((symbol-function 'noema-agent-render-flush) #'ignore))
            (my/vterm-popup-display-buffer term)
            (let ((window (my/vterm-popup--window)))
              (should (eq (my/vterm-popup-agent 'codex) agent))
              (should (equal (plist-get started :config) '(codex)))
              (should-not (plist-get started :focus))
              (should (eq (my/vterm-popup--window) window))
              (should (eq (window-buffer window) agent))
              (with-current-buffer agent
                (should (eq major-mode 'agent-shell-mode))
                (should my/vterm-popup-instance-p)
                (should-not noema-agent-acp-tabs-mode)
                (should (equal header-line-format "native ACP header"))
                (should (eq (key-binding (kbd "C-c C-e")) #'vterm-toggle))
                (should (eq (key-binding (kbd "C-c E")) #'my/vterm-popup-cycle))
                (should (eq (key-binding (kbd "C-c M-e")) #'my/vterm-toggle-fixed)))
              ;; ACP redisplay must not move the popup session to the project window.
              (noema-agent-acp-show-buffer agent)
              (should (eq (my/vterm-popup--window) window))
              (my/vterm-popup-cycle nil)
              (should (eq (window-buffer window) term))
              (my/vterm-popup-cycle nil)
              (should (eq (window-buffer window) agent))
              (vterm-toggle)
              (should-not (my/vterm-popup--window))
              (should (buffer-live-p agent))
              (vterm-toggle)
              (should (eq (window-buffer (my/vterm-popup--window)) agent))
              (my/vterm-toggle-fixed)
              (should (buffer-local-value 'my/vterm-popup-fixed agent))))
        (my/vterm-hide-popup)
        (kill-buffer agent)
        (kill-buffer term)))))

(ert-deftest popup-agent-entrypoints-select-the-corresponding-adapter ()
  (let (started)
    (cl-letf (((symbol-function 'my/vterm-popup-agent) (lambda (id) (push id started))))
      (my/vterm-popup-agent-claude)
      (my/vterm-popup-agent-codex)
      (my/vterm-popup-agent-opencode))
    (should (equal (nreverse started) '(claude codex opencode)))))

;;; popup-agent-tests.el ends here
