;;; remote-jupyter-tests.el --- Contents filesystem contract -*- lexical-binding: t; -*-
(require 'ert)
(require 'remote-framework)
(require 'remote-backend-jupyter)
(require 'cl-lib)

(defmacro remote-jupyter-tests--with-store (&rest body)
  `(let* ((my/noema-jupyter-servers '((:id "test-lab" :url "http://invalid.example/")))
          (store (make-hash-table :test #'equal))
          (root (remote-make-file-name (remote-jupyter-target-id "test-lab") "/")))
     (remote-jupyter-register)
     (remote-fs-install)
     (puthash "" :directory store)
     (cl-labels ((model (path)
                   `((path . ,path) (name . ,(file-name-nondirectory path))
                     (type . ,(if (eq (gethash path store) :directory) "directory" "file"))
                     (size . 42) (writable . t)
                     (created . "2026-09-26T00:00:00Z") (lastModified . "2026-09-26T00:00:01Z"))))
       (cl-letf (((symbol-function 'my/noema--api-call-sync)
                  (lambda (_channel args &optional _timeout)
                    (let* ((body (aref args 0)) (path (alist-get 'path body))
                           (operation (alist-get 'operation body)) (value (gethash path store)))
                      (cond
                       ((equal operation "write") (puthash path (base64-decode-string (alist-get 'content body)) store) '((ok . t)))
                       ((equal operation "mkdir") (puthash path :directory store) '((ok . t)))
                       ((not value) '((ok . :json-false) (error . ((code . "ENOENT") (message . "missing")))))
                       ((equal operation "stat") `((ok . t) (model . ,(model path))))
                       ((equal operation "read") `((ok . t) (content . ,(base64-encode-string value t))))
                       ((equal operation "list")
                        `((ok . t) (model . ,(model path))
                          (entries . ,(vconcat (cl-loop for key being the hash-keys of store
                                                       unless (or (equal key "") (string-match-p "/" key))
                                                       collect (model key))))))
                       ((equal operation "rename") (puthash (alist-get 'to body) value store) (remhash path store) '((ok . t)))
                       ((equal operation "delete") (remhash path store) '((ok . t)))
                       (t (error "Unexpected test operation %s" operation)))))))
         ,@body))))

(ert-deftest remote-jupyter-logical-files-read-write-rename-and-complete ()
  (remote-jupyter-tests--with-store
   (let ((file (concat root "résumé.txt")) (renamed (concat root "next.txt")))
     (with-temp-buffer (insert "λ notebook\n") (write-region nil nil file nil 'silent))
     (should (file-exists-p file))
     (should (file-regular-p file))
     (should-not (remote-client-file-name file))
     (with-temp-buffer
       (insert-file-contents file t)
       (should (equal (buffer-string) "λ notebook\n"))
       (should (equal buffer-file-name file)))
     (should (member "résumé.txt" (directory-files root)))
     (should (equal (file-name-all-completions "ré" root) '("résumé.txt")))
     (rename-file file renamed)
     (should-not (file-exists-p file))
     (should (file-exists-p renamed))
     (delete-file renamed)
     (should-not (file-exists-p renamed)))))

(ert-deftest remote-jupyter-does-not-fall-through-to-native-filesystem ()
  (remote-jupyter-tests--with-store
   (should-not (file-exists-p (concat root "etc/passwd")))
   (should-error (set-file-modes (concat root "etc/passwd") #o600) :type 'file-error)
   (should-error (remote-exec "python3" :args '("-V") :context (remote-context root)))
   (let ((default-directory root))
     (should-not (exec-path))
     (let ((failure (should-error (process-file "ls" nil nil nil "--version")
                                  :type 'file-error)))
       (should (string-match-p "process-sync" (error-message-string failure)))))
   (cl-letf (((symbol-function 'my/noema--api-call-sync)
              (lambda (&rest _) '((ok . :json-false) (error . ((code . "EACCES") (message . "denied")))))))
     (should-error (file-exists-p (concat root "exists.txt")) :type 'file-error))))

(ert-deftest remote-jupyter-dired-renders-through-directory-api ()
  (remote-jupyter-tests--with-store
   (require 'dired)
   (puthash "notebook.ipynb" "{}" store)
   (let ((buffer (dired-noselect root "-al")))
     (unwind-protect
         (with-current-buffer buffer
           (should (string-match-p "notebook.ipynb" (buffer-string)))
           (should (equal default-directory root)))
       (kill-buffer buffer)))))

(ert-deftest remote-jupyter-file-visits-keep-lexical-paths-and-find-ancestors ()
  (remote-jupyter-tests--with-store
   (puthash "project.txt" "x" store)
   (should (equal (file-name-sans-versions (concat root "note.ipynb~"))
                  (concat root "note.ipynb")))
   (should (equal (locate-dominating-file root "project.txt") root))))

(ert-deftest remote-jupyter-removed-servers-lose-their-mounts ()
  (remote-jupyter-tests--with-store
   (let ((id (remote-jupyter-target-id "test-lab")))
     (should (remote-get-target id))
     (let (my/noema-jupyter-servers) (remote-jupyter-register))
     (should-not (remote-get-target id))
     (should-not (remote-links-for-target id)))))
