;;; bootstrap.el --- Bootstrap packages from lock file -*- lexical-binding: t; -*-

;; 调整 GC，安装阶段更快
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6)

(require 'cl-lib)
(require 'package)

;; 仓库按需改
(setq package-archives
      '(("melpa"  . "https://melpa.org/packages/")
        ("gnu"    . "https://elpa.gnu.org/packages/")
        ("nongnu" . "https://elpa.nongnu.org/nongnu/")
        ("org"    . "https://orgmode.org/elpa/")))

(setq package-enable-at-startup nil)
(package-initialize)

;; ------------------------------------------------------------
;; 配置：你的 init.el 和 lock 文件路径
;; ------------------------------------------------------------

(defconst my/bootstrap-init-file
  (expand-file-name "init.el" user-emacs-directory)
  "Path to the real init.el that defines all use-package config.")

(defconst my/bootstrap-lock-file
  (expand-file-name "package-lock.el" user-emacs-directory)
  "Path to the package lock file storing package metadata.")

(defconst my/bootstrap-flag-var
  'my/bootstrap-has-run
  "Feature/variable name used to detect an already bootstrapped environment.")

(defconst my/bootstrap-min-old-env-package-count 3
  "Installed package count threshold used to detect an existing environment.")

(defconst my/bootstrap-core-packages
  '(use-package)
  "Packages that should not count toward the old-environment heuristic.")

(defvar my/bootstrap--archives-refreshed nil
  "Whether package archives have already been refreshed in this run.")

;; ------------------------------------------------------------
;; Helpers
;; ------------------------------------------------------------

(defun my/bootstrap-refresh-archives-once ()
  "Refresh package archives once per bootstrap run."
  (unless (or my/bootstrap--archives-refreshed
              package-archive-contents)
    (message "Refreshing package archives...")
    (package-refresh-contents)
    (setq my/bootstrap--archives-refreshed t)))

(defun my/bootstrap-ensure-package-installed (pkg)
  "Install archive package PKG if it is missing."
  (unless (package-installed-p pkg)
    (my/bootstrap-refresh-archives-once)
    (message "Installing %s..." pkg)
    (package-install pkg)))

(defun my/bootstrap--package-desc (pkg)
  "Return the first package descriptor for PKG from `package-alist'."
  (cadr (assq pkg package-alist)))

(defun my/bootstrap--vc-package-p (pkg)
  "Return non-nil if PKG is installed as a VC package."
  (let ((desc (my/bootstrap--package-desc pkg)))
    (eq (and desc (package-desc-kind desc)) 'vc)))

(defun my/bootstrap--installed-third-party-packages ()
  "Return currently installed third-party packages excluding bootstrap essentials."
  (let ((pkgs nil))
    (dolist (entry package-alist)
      (let ((pkg (car entry)))
        (unless (memq pkg my/bootstrap-core-packages)
          (push pkg pkgs))))
    (sort pkgs (lambda (a b) (string< (symbol-name a) (symbol-name b))))))

(defun my/bootstrap--current-package-list ()
  "Return installed non-VC packages in stable order."
  (let ((vc-names (mapcar #'car (my/bootstrap--current-vc-package-list))))
    (cl-remove-if (lambda (pkg)
                    (or (memq pkg vc-names)
                        (my/bootstrap--vc-package-p pkg)))
                  (my/bootstrap--installed-third-party-packages))))

(defun my/bootstrap--current-vc-package-list ()
  "Return VC package specs collected from init declarations and package state."
  (let ((merged nil))
    (dolist (entry (append (and (boundp 'my/package-vc-recipes)
                                (copy-tree my/package-vc-recipes))
                           (and (boundp 'package-vc-selected-packages)
                                (copy-tree package-vc-selected-packages))))
      (pcase-let ((`(,name . ,spec) entry))
        (setq merged (assq-delete-all name merged))
        (push (cons name spec) merged)))
    (sort merged
          (lambda (a b)
            (string< (symbol-name (car a))
                     (symbol-name (car b)))))))

(defun my/bootstrap-write-lock-file ()
  "Write installed archive and VC packages to `my/bootstrap-lock-file'."
  (let ((pkgs (my/bootstrap--current-package-list))
        (vc-pkgs (my/bootstrap--current-vc-package-list)))
    (with-temp-file my/bootstrap-lock-file
      (insert ";;; package-lock.el --- Generated by bootstrap.el -*- lexical-binding: t; -*-\n\n")
      (insert ";; 自动生成的包锁文件：普通包走 package-install，VC 包走 package-vc-install。\n\n")
      (insert "(setq my/package-lock-version 2)\n\n")
      (insert "(setq package-selected-packages\n      '")
      (prin1 pkgs (current-buffer))
      (insert ")\n\n")
      (insert "(setq package-vc-selected-packages\n      '")
      (prin1 vc-pkgs (current-buffer))
      (insert ")\n\n")
      (insert "(provide 'package-lock)\n"))))

(defun my/bootstrap-read-lock-file ()
  "Load `my/bootstrap-lock-file' if it exists."
  (when (file-exists-p my/bootstrap-lock-file)
    (load-file my/bootstrap-lock-file)))

(defun my/bootstrap-install-archive-packages-from-lock ()
  "Install archive packages from `package-selected-packages'."
  (when (boundp 'package-selected-packages)
    (dolist (pkg package-selected-packages)
      (unless (package-installed-p pkg)
        (condition-case err
            (my/bootstrap-ensure-package-installed pkg)
          (error
           (message "Failed to install archive package %s: %s"
                    pkg (error-message-string err))))))))

(defun my/bootstrap-install-vc-packages-from-lock ()
  "Install VC packages from `package-vc-selected-packages'."
  (when (boundp 'package-vc-selected-packages)
    (require 'package-vc)
    (dolist (entry package-vc-selected-packages)
      (pcase-let ((`(,pkg . ,spec) entry))
        (unless (package-installed-p pkg)
          (condition-case err
              (progn
                (my/bootstrap-refresh-archives-once)
                (message "Installing VC package %s..." pkg)
                (cond
                 ((null spec)
                  (package-vc-install pkg))
                 ((stringp spec)
                  (package-vc-install pkg spec))
                 ((listp spec)
                  (package-vc-install (cons pkg spec)))
                 (t
                  (error "Unsupported VC package spec: %S" spec))))
            (error
             (message "Failed to install VC package %s: %s"
                      pkg (error-message-string err)))))))))

;; ------------------------------------------------------------
;; Main flow
;; ------------------------------------------------------------

(defun my/bootstrap-old-env-p ()
  "Detect whether this looks like an existing local environment.

The heuristic is intentionally simple: if there are already enough
third-party packages installed locally, treat this machine as the
source environment and export a fresh lock file; otherwise, treat it as
the target environment and install from the checked-in lock file."
  (or (featurep my/bootstrap-flag-var)
      (boundp my/bootstrap-flag-var)
      (>= (length (my/bootstrap--installed-third-party-packages))
          my/bootstrap-min-old-env-package-count)))

(defun my/bootstrap-run ()
  "Main entry for bootstrap."
  (my/bootstrap-ensure-package-installed 'use-package)
  (require 'use-package)

  (if (my/bootstrap-old-env-p)
      (progn
        (message "Detected existing environment. Loading init.el and exporting package-lock.el...")
        (when (file-exists-p my/bootstrap-init-file)
          (load-file my/bootstrap-init-file))
        (my/bootstrap-write-lock-file)
        (message "package-lock.el generated at %s" my/bootstrap-lock-file))
    (progn
      (message "Detected fresh environment. Bootstrapping from package-lock.el...")
      (my/bootstrap-read-lock-file)
      (if (or (boundp 'package-selected-packages)
              (boundp 'package-vc-selected-packages))
          (progn
            (my/bootstrap-install-archive-packages-from-lock)
            (my/bootstrap-install-vc-packages-from-lock))
        (message "No package-lock.el found. Only use-package is ensured; rest will be installed lazily."))))

  ;; 恢复 GC 设置 + 退出
  (setq gc-cons-threshold (* 64 1024 1024)
        gc-cons-percentage 0.1)
  (message "Bootstrap finished. You can now restart Emacs with your normal init.")
  (run-at-time
   "1 sec" nil
   (lambda ()
     (save-some-buffers t)
     (kill-emacs 0))))

(my/bootstrap-run)

(provide 'bootstrap)
;;; bootstrap.el ends here
