;;; bootstrap.el --- One-shot bootstrap with package lock  -*- lexical-binding: t; -*-

;; 调整 GC，安装阶段更快
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.6)

(require 'package)

;; 仓库按需改
(setq package-archives
      '(("gnu"   . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))

(setq package-enable-at-startup nil)
(package-initialize)

(unless package-archive-contents
  (message "Refreshing package archives...")
  (package-refresh-contents))

;; 确保 use-package 存在
(unless (package-installed-p 'use-package)
  (message "Installing use-package...")
  (package-install 'use-package))

(require 'use-package)
(require 'use-package-ensure)
(setq use-package-always-ensure t)

;; ------------------------------------------------------------
;; 配置：你的 init.el 和 lock 文件路径
;; ------------------------------------------------------------

(defconst my/bootstrap-init-file
  (expand-file-name "init.el" user-emacs-directory)
  "Path to the real init.el that defines all use-package config.")

(defconst my/bootstrap-lock-file
  (expand-file-name "package-lock.el" user-emacs-directory)
  "Path to the package lock file storing installed packages list.")

(defconst my/bootstrap-flag-var
  'my/bootstrap-has-run
  "Feature/variable name used to detect old environment.")

;; ------------------------------------------------------------
;; 工具：生成 / 读取 package-lock.el
;; ------------------------------------------------------------

(defun my/bootstrap--current-package-list ()
  "Return a list of non-built-in installed packages."
  ;; 更粗暴但简单：用 package-alist 的 key；内置包通常不在 package-user-dir 里。[web:55][web:59]
  (mapcar #'car package-alist))

(defun my/bootstrap-write-lock-file ()
  "Write currently installed packages list to `my/bootstrap-lock-file`."
  (let ((pkgs (my/bootstrap--current-package-list)))
    (with-temp-file my/bootstrap-lock-file        ;; 原子写文件 [web:61]
      (insert ";;; package-lock.el --- Generated by bootstrap.el\n\n")
      (insert ";; 自动生成的已安装包列表，用于新环境同步。\n\n")
      (insert "(setq package-selected-packages\n      '")
      (prin1 pkgs (current-buffer))               ;; 以 Lisp 语法打印列表 [web:57]
      (insert ")\n\n(provide 'package-lock)\n"))))

(defun my/bootstrap-read-lock-file ()
  "Load `my/bootstrap-lock-file` if it exists."
  (when (file-exists-p my/bootstrap-lock-file)
    (load-file my/bootstrap-lock-file)))          ;; 里面设置 package-selected-packages [web:59]

(defun my/bootstrap-install-from-lock ()
  "Install packages from `package-selected-packages`."
  (when (boundp 'package-selected-packages)
    (dolist (pkg package-selected-packages)
      (unless (package-installed-p pkg)
        (message "Installing %s from lock..." pkg)
        (ignore-errors
          (package-install pkg))))))

;; ------------------------------------------------------------
;; 主逻辑：
;; 1. 如果检测到是“旧环境”（有标记 var），就：
;;    - 加载 init.el
;;    - 生成/更新 package-lock.el
;; 2. 否则：新环境
;;    - 读取 lock 文件（如果有）并按其中列表安装
;;    - 没有 lock 时，只装 use-package + 你手写的一小批基础包（可选）
;; ------------------------------------------------------------

(defun my/bootstrap-old-env-p ()
  "Detect whether this is an \"old\" env that already has init/marker."
  (or (featurep my/bootstrap-flag-var)
      (boundp my/bootstrap-flag-var)
      ;; 粗暴一点：如果 init.el 存在且能加载，就视为旧环境
      (file-exists-p my/bootstrap-init-file)))

(defun my/bootstrap-run ()
  "Main entry for bootstrap."
  (if (my/bootstrap-old-env-p)
      ;; 旧环境：加载 init.el，并导出 package-lock
      (progn
        (message "Detected old environment. Loading init.el and exporting package-lock.el...")
        (when (file-exists-p my/bootstrap-init-file)
          (load-file my/bootstrap-init-file))
        (my/bootstrap-write-lock-file)
        (message "package-lock.el generated at %s" my/bootstrap-lock-file))
    ;; 新环境：根据 lock 安装
    (progn
      (message "New environment detected. Bootstrapping from package-lock.el (if present)...")
      (my/bootstrap-read-lock-file)
      (if (boundp 'package-selected-packages)
          (progn
            (message "Installing packages from package-lock.el...")
            (my/bootstrap-install-from-lock))
        (message "No package-lock.el found. Only use-package is ensured; rest will be installed lazily."))))

  ;; 恢复 GC 设置 + 退出
  (setq gc-cons-threshold (* 64 1024 1024)
        gc-cons-percentage 0.1)
  (message "Bootstrap finished. You can now restart Emacs with your normal init.")
  (run-at-time
   "1 sec" nil
   (lambda ()
     (save-some-buffers t)
     (kill-emacs 0))))

(my/bootstrap-run)

(provide 'bootstrap)
;;; bootstrap.el ends here
