;;; package-lock.el --- Generated by bootstrap.el -*- lexical-binding: t; -*-

;; 自动生成的包锁文件：普通包走 package-install，VC 包走 package-vc-install。

(setq my/package-lock-version 2)

(setq package-selected-packages
      '(ace-window aggressive-indent amx annalist ansi async atomic-chrome auctex avy bazel better-jumper biblio biblio-core bibtex-completion bison-mode breadcrumb browse-at-remote bui caml cdlatex centaur-tabs cfrs citeproc citre cmake-font-lock cmake-mode code-cells company company-box company-prescient cond-let consult consult-dir copilot counsel counsel-projectile dape dash dashboard deferred deflate devdocs diff-hl diredfl direnv dirvish doom-modeline dtrt-indent edit-indirect eldoc-box elisp-refs elsa emacsql embark embark-consult evil evil-collection evil-surround exec-path-from-shell f fanyi flymake-diagnostic-at-point frame-local fzf gcmh gnuplot goto-chg gptel graphviz-dot-mode haskell-mode helpful hl-todo ht htmlize hydra ibuffer-projectile ibuffer-vc indent-guide ivy ivy-posframe js2-mode jupyter kanagawa-themes lgr link-hint llama lsp-mode lv magit magit-delta magit-section marginalia mermaid-mode mixed-pitch msgpack mwim nerd-icons nix-mode no-littering ob-mermaid ob-rust olivetti orderless org-contrib org-fancy-priorities org-fragtog org-modern org-ref org-roam org-roam-ui org-superstar outline-indent ox-pandoc parsebib pdf-tools perspective pfuture plantuml-mode popper popup posframe powerline prescient projectile quelpa queue quickrun rainbow-delimiters rainbow-mode request restart-emacs rg rmsbolt rust-mode s scala-mode separedit shackle shrink-path simple-httpd smartparens spdx spinner string-inflection swiper tablist treemacs treemacs-evil treemacs-magit treemacs-projectile treesit-auto trinary try tuareg undo-tree use-package-hydra valign vertico vlf vterm vue-html-mode webpaste websocket wgrep with-editor ws-butler xterm-color yaml yaml-mode yasnippet yasnippet-snippets zmq))

(setq package-vc-selected-packages
      '((all-the-icons :url "https://github.com/domtronn/all-the-icons.el.git" :rev :last-release) (flymake-vale :url "https://github.com/tpeacock19/flymake-vale.git" :rev :last-release) (joplin-mode :url "https://github.com/cinsk/joplin-mode.git" :rev :last-release) (lean4-mode :url "https://github.com/leanprover-community/lean4-mode.git" :rev :last-release) (markdown-mode :url "https://github.com/jrblevin/markdown-mode.git" :rev :last-release) (treesit-fold :url "https://github.com/emacs-tree-sitter/treesit-fold.git" :rev :last-release)))

(provide 'package-lock)
