;;; config-noema.el --- generated by config.el -*- lexical-binding: t; -*-
;; Auto-generated.  Do not edit by hand; use `config-set' or the board.

(config-store-set
 '((noema-pi-auto-start . t) (noema-pi-stop-delay . 30)
   (noema-pi-model . "") (noema-pi-thinking-level . "off"))
)
