;;; config-treesit.el --- generated by config.el -*- lexical-binding: t; -*-
;; Auto-generated.  Do not edit by hand; use `config-set' or the board.

(config-store-set
 '((jit-lock-context-time . 0.2) (jit-lock-chunk-size . 4096)
   (jit-lock-stealth-time) (idle-update-delay . 5.0)
   (treesit-extra-load-path "/Users/hc/.emacs.d/var/tree-sitter/")
   (treesit-language-source-alist
    (bash "https://github.com/tree-sitter/tree-sitter-bash")
    (c "https://github.com/tree-sitter/tree-sitter-c")
    (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
    (css "https://github.com/tree-sitter/tree-sitter-css")
    (go "https://github.com/tree-sitter/tree-sitter-go")
    (html "https://github.com/tree-sitter/tree-sitter-html")
    (java "https://github.com/tree-sitter/tree-sitter-java")
    (javascript "https://github.com/tree-sitter/tree-sitter-javascript")
    (jsdoc "https://github.com/tree-sitter/tree-sitter-jsdoc")
    (json "https://github.com/tree-sitter/tree-sitter-json")
    (python "https://github.com/tree-sitter/tree-sitter-python")
    (rust "https://github.com/tree-sitter/tree-sitter-rust")
    (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master"
         "tsx/src")
    (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master"
                "typescript/src")
    (toml "https://github.com/tree-sitter/tree-sitter-toml")
    (yaml "https://github.com/ikatyang/tree-sitter-yaml")))
)
