;;; config-ai.el --- generated by config.el -*- lexical-binding: t; -*-
;; Auto-generated.  Do not edit by hand; use `config-set' or the board.

(config-store-set
 '((codex-cli-width . 90) (codex-cli-side . right)
   (codex-cli-terminal-backend . vterm) (codex-cli-executable . "codex")
   (claude-code-ide-window-width . 90) (claude-code-ide-window-side . right)
   (claude-code-ide-cli-path . "/Users/hc/.local/bin/claude"))
)
