;;; config-libraries.el --- generated by config.el -*- lexical-binding: t; -*-
;; Auto-generated.  Do not edit by hand; use `config-set' or the board.

(config-store-set
 '((thing-edit-flash-line-delay . 0.3) (thing-edit-show-message-p . t)
   (fingertip-save-in-kill-ring . t) (symbol-overlay-jump-hook)
   (symbol-overlay-priority)
   (symbol-overlay-ignore-functions (c-mode . symbol-overlay-ignore-function-c)
                                    (c++-mode . symbol-overlay-ignore-function-c++)
                                    (python-mode
                                     . symbol-overlay-ignore-function-python)
                                    (java-mode
                                     . symbol-overlay-ignore-function-java)
                                    (go-mode . symbol-overlay-ignore-function-go))
   (symbol-overlay-overlay-created-functions) (symbol-overlay-idle-time . 0.5)
   (symbol-overlay-temp-highlight-single) (symbol-overlay-displayed-window . t)
   (symbol-overlay-faces symbol-overlay-face-1 symbol-overlay-face-2
                         symbol-overlay-face-3 symbol-overlay-face-4
                         symbol-overlay-face-5 symbol-overlay-face-6
                         symbol-overlay-face-7 symbol-overlay-face-8)
   (winpoint-non-restore-buffer-list))
)
