;;; config-snippets.el --- generated by config.el -*- lexical-binding: t; -*-
;; Auto-generated.  Do not edit by hand; use `config-set' or the board.

(config-store-set
 '((yas-snippet-dirs . ("/Users/hc/.emacs.d/snippets")))
)
