;;; config-browser.el --- generated by config.el -*- lexical-binding: t; -*-
;; Auto-generated.  Do not edit by hand; use `config-set' or the board.

(config-store-set
 '((xwidget-webkit-cookie-file
    . "/Users/hc/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies")
   (xwidget-webkit-cache-directory
    . "/Users/hc/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cache/")
   (xwidget-webkit-local-storage-directory
    . "/Users/hc/Library/Application Support/BraveSoftware/Brave-Browser/Default/Local Storage/")
   (xwidget-webkit-enable-javascript . t)
   (xwidget-webkit-enable-plugins . t)
   (xwidget-webkit-enable-media . t)
   (xwidget-webkit-user-agent
    . "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
   (xwidget-webkit-enable-developer-extras . t)
   (xwidget-webkit-buffer-name-format . "*xwidget*")
   (browse-url-browser-function . my/browse-url)
   (eww-search-prefix . "https://duckduckgo.com/?q="))
)
