;;; config-output.el --- generated by config.el -*- lexical-binding: t; -*-
;; Auto-generated.  Do not edit by hand; use `config-set' or the board.

(config-store-set
 '((my/output-interesting-buffer-regexp . "\\*\\(?:compilation\\|test\\|task\\|run\\)\\*"))
)
