;;; init-treemacs-bridge.el --- Treemacs bridge declarations and repair helpers -*- lexical-binding: t; -*-

;;; Commentary:
;;

;;; Code:

(require 'init-funcs)

(declare-function my/treemacs-cursor-follow-mode "init-project" (&optional arg))
(declare-function my/treemacs-reset-follow-state "init-project")

(eval-and-compile
  (defmacro my/treemacs-bridge-declarations ()
    "Inject Treemacs and perspective declarations into the current file."
    '(progn
       (declare-function persp-kill "perspective" (name))
       (declare-function persp-kill-buffer* "perspective" (&optional buffer))
       (declare-function persp-names "perspective")
       (declare-function persp-switch "perspective" (name &optional auto-save reset))
       (declare-function treemacs "treemacs" (&optional arg))
       (declare-function treemacs-add-and-display-current-project-exclusively "treemacs")
       (declare-function treemacs-default-buffer-name "treemacs")
       (declare-function treemacs-delete-other-windows "treemacs")
       (declare-function treemacs-do-add-project-to-workspace "treemacs-workspaces" (path name))
       (declare-function treemacs-filewatch-mode "treemacs-filewatch-mode" (&optional arg))
       (declare-function treemacs-find-file "treemacs")
       (declare-function treemacs-find-tag "treemacs")
       (declare-function treemacs-follow-mode "treemacs-follow-mode" (&optional arg))
       (declare-function treemacs-fringe-indicator-mode "treemacs-fringe-indicator-mode" (&optional arg))
       (declare-function treemacs-get-local-window "treemacs")
       (declare-function treemacs-git-commit-diff-mode "treemacs-git-commit-diff-mode" (&optional arg))
       (declare-function treemacs-git-mode "treemacs-git-mode" (mode))
       (declare-function treemacs-goto-file-node "treemacs" (path project))
       (declare-function treemacs-hide-gitignored-files-mode "treemacs" (&optional arg))
       (declare-function treemacs-project-follow-mode "treemacs-project-follow-mode" (&optional arg))
       (declare-function treemacs-refresh "treemacs")
       (declare-function treemacs-select-directory "treemacs")
       (declare-function treemacs-select-window "treemacs")
       (declare-function treemacs-set-scope-type "treemacs" (scope))
       (declare-function treemacs-single-click-expand-action "treemacs")
       (declare-function treemacs-tag-follow-mode "treemacs-tag-follow-mode" (&optional arg))
       (declare-function treemacs-workspace->projects "treemacs-workspaces" (workspace))
       (declare-function treemacs-workspace->name "treemacs-workspaces" (workspace))
       (declare-function treemacs-workspaces "treemacs-workspaces")
       (declare-function treemacs-current-workspace "treemacs-workspaces")
       (declare-function treemacs-disabled-workspaces "treemacs-workspaces")
       (declare-function treemacs-project->name "treemacs-workspaces" (project))
       (declare-function treemacs-project->path "treemacs-workspaces" (project))
       (declare-function treemacs--compare-markdown-tag-paths "treemacs-tags" (a b))
       (declare-function treemacs--compare-tag-paths "treemacs-tags" (a b))
       (declare-function treemacs--do-follow-tag "treemacs-tag-follow-mode" (index window path project))
       (declare-function treemacs--find-project-for-buffer "treemacs-project-follow-mode" (path))
       (declare-function treemacs--flatten-imenu-index "treemacs-tags" (index))
       (declare-function treemacs--flatten-org-mode-imenu-index "treemacs-tags" (index))
       (declare-function treemacs--get-imenu-index "treemacs-tags" (filename))
       (declare-function treemacs--invalidate-buffer-project-cache "treemacs-project-follow-mode")
       (declare-function treemacs--persist "treemacs-persistence")
       (declare-function treemacs--rerender-after-workspace-change "treemacs-rendering")
       (declare-function (setf treemacs-workspace->projects) "treemacs-workspaces" (value workspace))
       (defvar evil-treemacs-state-map)
       (defvar my/treemacs-cursor-follow-mode)
       (defvar treemacs--imenu-cache)
       (defvar treemacs--project-of-buffer)
       (defvar treemacs-follow-mode)
       (defvar treemacs-disabled-workspaces)
       (defvar treemacs-mode-map)
       (defvar treemacs-project-follow-mode)
       (defvar treemacs-pulse-on-failure)
       (defvar treemacs-python-executable)
       (defvar treemacs-scope-types)
       (defvar treemacs-tag-follow-mode)
       (defvar winum-keymap)))
  (my/treemacs-bridge-declarations))

(defun my/treemacs-repair-workspace ()
  "Refresh Treemacs and reapply active follow modes."
  (interactive)
  (unless (require 'treemacs nil t)
    (user-error "Treemacs is unavailable"))
  (let ((follow (bound-and-true-p treemacs-follow-mode))
        (project-follow (bound-and-true-p treemacs-project-follow-mode))
        (cursor-follow (bound-and-true-p my/treemacs-cursor-follow-mode)))
    (when (fboundp 'my/treemacs-reset-follow-state)
      (my/treemacs-reset-follow-state))
    (when (fboundp 'treemacs-refresh)
      (treemacs-refresh))
    (when (and follow (fboundp 'treemacs-follow-mode))
      (treemacs-follow-mode 1))
    (when (and project-follow (fboundp 'treemacs-project-follow-mode))
      (treemacs-project-follow-mode 1))
    (when (and cursor-follow (fboundp 'my/treemacs-cursor-follow-mode))
      (my/treemacs-cursor-follow-mode 1))
    (message "Treemacs workspace refreshed")))

(my/leader!
  "p T" '(:def my/treemacs-repair-workspace :which-key "repair treemacs"))

(provide 'init-treemacs-bridge)
;;; init-treemacs-bridge.el ends here
