;;; init-browser.el --- Browser integration -*- lexical-binding: t -*-

;;; Commentary:
;;

;;; Code:

(require 'config)
;;;

(require 'general)
(require 'cl-lib)
(require 'subr-x)
(require 'url-parse)
(require 'easymenu)
(require 'init-open)

(declare-function appine-open-url "appine" (url))
(declare-function my/appine-get-url "init-appine" ())
(declare-function my/appine-kill-all "init-appine" ())
(declare-function my/appine-back "init-appine" ())
(declare-function my/appine-close-tab "init-appine" ())
(declare-function my/appine-forward "init-appine" ())
(declare-function my/appine-next-tab "init-appine" ())
(declare-function my/appine-open-url "init-appine" (url))
(declare-function my/appine-open-file "init-appine" (path))
(declare-function my/appine-open-at-point "init-appine" ())
(declare-function my/appine-prev-tab "init-appine" ())
(declare-function my/appine-reload "init-appine" ())
(declare-function my/macos-open-url "init-macos" (url))
(declare-function my/open-normalize-backend "init-open" (backend))
(declare-function my/open-eww-url "init-open" (url &optional reuse-selected))
(declare-function my/open-read-backend "init-open" (kind &optional prompt default))
(declare-function my/open-resolve-backend "init-open" (kind &optional backend))
(declare-function my/open-url "init-open" (url &optional backend))
(declare-function my/open-url-with-backend "init-open" (url backend &optional reuse-selected))
(declare-function my/open--with-browser-window "init-open" (mode reuse-selected open-fn))
(declare-function my/open-normalize-url "init-open" (url))
(declare-function nerd-icons-mdicon "nerd-icons" (icon-name &rest args))
(declare-function nerd-icons-codicon "nerd-icons" (icon-name &rest args))

;;;; xwidget API

(defvar my/xwidget--sessions (make-hash-table :test #'equal)
  "Stable xwidget session id to buffer map.")

(defvar my/xwidget--session-counter 0
  "Counter used for anonymous xwidget session ids.")

(defvar-local my/xwidget-session-url nil
  "Last URL recorded for this xwidget buffer.")

(defvar-local my/xwidget-session-title nil
  "Last page title recorded for this xwidget buffer.")

(defvar-local my/xwidget--managed-buffer-name nil
  "Last buffer name generated by the xwidget naming helper.")

(defvar-local my/xwidget--session-id nil
  "Session id for this xwidget buffer, used to remove its hash entry on kill.")

(defun my/xwidget--session-cleanup ()
  "Remove this buffer's entry from `my/xwidget--sessions' when the buffer is killed."
  (when my/xwidget--session-id
    (remhash my/xwidget--session-id my/xwidget--sessions)))

(config-defvar my/xwidget-auto-focus-on-load nil
  "Auto-focus xwidget buffer when its page finishes loading."
  :type 'boolean
  :group 'xwidget)

(defvar-local my/xwidget-suppress-auto-focus nil
  "Non-nil means this xwidget buffer must not auto-focus on load/reuse.")
(put 'my/xwidget-suppress-auto-focus 'permanent-local t)

(defvar-local my/xwidget-focus-script nil
  "Optional JS to focus an editable element inside this xwidget buffer.
Set buffer-locally before the page loads (e.g. in the open function).")
(put 'my/xwidget-focus-script 'permanent-local t)

(defun my/xwidget--auto-focus-allowed-p (&optional buffer)
  "Return non-nil when BUFFER may receive automatic xwidget focus."
  (let ((buf (or buffer (current-buffer))))
    (and my/xwidget-auto-focus-on-load
         (buffer-live-p buf)
         (with-current-buffer buf
           (not my/xwidget-suppress-auto-focus)))))

(defun my/xwidget-focus (&optional buffer)
  "Focus the xwidget in BUFFER (default: current buffer) for keyboard input.
Enables edit-mode, runs any buffer-local JS focus script, and switches
to evil insert state if evil is active in the buffer."
  (interactive)
  (let ((buf (or buffer (current-buffer))))
    (when (and (buffer-live-p buf)
               (with-current-buffer buf
                 (eq major-mode 'xwidget-webkit-mode)))
      (with-current-buffer buf
        (when (fboundp 'xwidget-webkit-edit-mode)
          (ignore-errors (xwidget-webkit-edit-mode 1)))
        (when-let* ((session (and (fboundp 'xwidget-webkit-current-session)
                                  (ignore-errors (xwidget-webkit-current-session)))))
          (when (and my/xwidget-focus-script
                     (fboundp 'xwidget-webkit-execute-script))
            (ignore-errors
              (xwidget-webkit-execute-script session my/xwidget-focus-script))))
))))

(defun my/xwidget--load-finished-focus (xwidget _xwidget-event-type)
  "Schedule focus for XWIDGET's buffer after page load-finished."
  ;; Capture the load-finished detail immediately (last-input-event is ephemeral).
  (when (and (eq _xwidget-event-type 'load-changed)
             (string-equal (nth 3 last-input-event) "load-finished"))
    (let ((buf (and (fboundp 'xwidget-buffer)
                    (ignore-errors (xwidget-buffer xwidget)))))
      (when (and (buffer-live-p buf)
                 (my/xwidget--auto-focus-allowed-p buf)
                 (or (eq buf (current-buffer))
                     (get-buffer-window buf)))
        ;; Delay 0.3 s to let WebKit finish rendering before injecting focus.
        (run-at-time 0.3 nil #'my/xwidget-focus buf)))))

(defun my/xwidget--callback-update-buffer-name (xwidget xwidget-event-type)
  "Update xwidget buffer name after title or load events."
  (when (memq xwidget-event-type '(document-title-changed title-changed load-changed))
    (let ((buf (and (fboundp 'xwidget-buffer)
                    (ignore-errors (xwidget-buffer xwidget)))))
      (when (buffer-live-p buf)
        (with-current-buffer buf
          (when (and (eq major-mode 'xwidget-webkit-mode)
                     (fboundp 'xwidget-webkit-title))
            (setq-local my/xwidget-session-title
                        (ignore-errors (xwidget-webkit-title xwidget))))
          (when (and (eq major-mode 'xwidget-webkit-mode)
                     (fboundp 'xwidget-webkit-uri))
            (setq-local my/xwidget-session-url
                        (ignore-errors (xwidget-webkit-uri xwidget)))))
        (my/xwidget-update-buffer-name buf)))))

(defun my/xwidget--ensure-available ()
  "Ensure native xwidget-webkit primitives are available."
  (unless (fboundp 'xwidget-webkit-browse-url)
    (require 'xwidget))
  (unless (fboundp 'xwidget-webkit-browse-url)
    (user-error "xwidget-webkit is not available in this Emacs")))

(defun my/xwidget-session-buffer (id)
  "Return live xwidget buffer for session ID, or nil."
  (let ((buffer (and id (gethash id my/xwidget--sessions))))
    (when (buffer-live-p buffer)
      buffer)))

(defun my/xwidget-current-url (&optional buffer)
  "Return current URL for xwidget BUFFER, defaulting to current buffer."
  (let ((buffer (or buffer (current-buffer))))
    (when (buffer-live-p buffer)
      (with-current-buffer buffer
        (or my/xwidget-session-url
            (and (eq major-mode 'xwidget-webkit-mode)
                 (fboundp 'xwidget-webkit-current-session)
                 (fboundp 'xwidget-webkit-uri)
                 (ignore-errors
                   (xwidget-webkit-uri (xwidget-webkit-current-session)))))))))

(defun my/xwidget-current-title (&optional buffer)
  "Return current page title for xwidget BUFFER, defaulting to current buffer."
  (let ((buffer (or buffer (current-buffer))))
    (when (buffer-live-p buffer)
      (with-current-buffer buffer
        (or my/xwidget-session-title
            (and (eq major-mode 'xwidget-webkit-mode)
                 (fboundp 'xwidget-webkit-current-session)
                 (fboundp 'xwidget-webkit-title)
                 (ignore-errors
                   (xwidget-webkit-title (xwidget-webkit-current-session)))))))))

(defun my/xwidget--clean-title (title)
  "Return TITLE trimmed for use in an xwidget buffer name, or nil."
  (when (stringp title)
    (let ((title (string-trim title)))
      (unless (or (string-empty-p title)
                  (string-match-p "\\`\\(?:about:blank\\|Loading\\.\\.\\.\\)\\'" title))
        (truncate-string-to-width title 80 nil nil t)))))

(defun my/xwidget--url-name-part (url)
  "Return a readable name derived from URL."
  (when (and (stringp url) (not (string-empty-p url)))
    (condition-case nil
        (let* ((parsed (url-generic-parse-url url))
               (host (url-host parsed))
               (path (url-filename parsed))
               (clean-path (and path (car (split-string path "[?#]" t))))
               (leaf (and clean-path
                          (not (string-empty-p clean-path))
                          (file-name-nondirectory
                           (directory-file-name clean-path)))))
          (or (my/xwidget--clean-title leaf)
              (my/xwidget--clean-title host)
              (my/xwidget--clean-title url)))
      (error
       (my/xwidget--clean-title url)))))

(defun my/xwidget--preferred-buffer-name (&optional buffer)
  "Return the preferred generated xwidget name for BUFFER."
  (let* ((buffer (or buffer (current-buffer)))
         (title (my/xwidget-current-title buffer))
         (url (my/xwidget-current-url buffer))
         (label (or (my/xwidget--clean-title title)
                    (my/xwidget--url-name-part url))))
    (when label
      (format "*xwidget: %s*" label))))

(defun my/xwidget--noema-owned-p (&optional buffer)
  "Return non-nil when BUFFER has Noema-specific naming."
  (let ((buffer (or buffer (current-buffer))))
    (and (buffer-live-p buffer)
         (with-current-buffer buffer
           (and (boundp 'my/noema--xwidget-forced-name)
                my/noema--xwidget-forced-name)))))

(defun my/xwidget-update-buffer-name (&optional buffer)
  "Rename BUFFER from its page title or URL when it is safe to do so."
  (let ((buffer (or buffer (current-buffer))))
    (when (buffer-live-p buffer)
      (with-current-buffer buffer
        (cond
         ((my/xwidget--noema-owned-p buffer)
          (unless (equal (buffer-name) my/noema--xwidget-forced-name)
            (rename-buffer my/noema--xwidget-forced-name t)))
         ((and (eq major-mode 'xwidget-webkit-mode)
               (not (minibufferp)))
          (when-let* ((name (my/xwidget--preferred-buffer-name buffer)))
            (when (or (null my/xwidget--managed-buffer-name)
                      (equal (buffer-name) my/xwidget--managed-buffer-name)
                      (string-match-p "\\`\\*xwidget\\*\\(?:<[0-9]+>\\)?\\'"
                                      (buffer-name)))
              (rename-buffer name t)
              (setq-local my/xwidget--managed-buffer-name (buffer-name))))))))))

(defun my/xwidget--record-buffer (buffer id url)
  "Record BUFFER as xwidget session ID with URL."
  (when (buffer-live-p buffer)
    (with-current-buffer buffer
      (unless (equal my/xwidget-session-url url)
        (setq-local my/xwidget-session-title nil))
      (setq-local my/xwidget-session-url url)
      (setq-local my/xwidget-suppress-auto-focus nil)
      (when id
        (setq-local my/xwidget--session-id id)
        (add-hook 'kill-buffer-hook #'my/xwidget--session-cleanup nil t)))
    (when id
      (puthash id buffer my/xwidget--sessions))
    (my/xwidget-update-buffer-name buffer)))

(defun my/xwidget--display-buffer (buffer display)
  "Display BUFFER according to DISPLAY."
  (pcase display
    ('none nil)
    ('current (switch-to-buffer buffer))
    (_ (pop-to-buffer buffer))))

(cl-defun my/xwidget-open-url (url &key id (display 'side) force-new reuse-selected)
  "Open URL through the customized xwidget API.
ID identifies a stable session.  DISPLAY may be `side', `current' or `none'.
When FORCE-NEW is non-nil, replace the old buffer for ID."
  (interactive
   (list (read-string "xwidget URL: ")
         :display 'side))
  (my/xwidget--ensure-available)
  (let* ((url (my/open-normalize-url url))
         (id (or id (format "xwidget-%d" (cl-incf my/xwidget--session-counter))))
         (existing (my/xwidget-session-buffer id)))
    (when (and existing force-new)
      (remhash id my/xwidget--sessions)
      (kill-buffer existing)
      (setq existing nil))
    (if existing
        (progn
          (if (and (fboundp 'xwidget-webkit-current-session)
                   (fboundp 'xwidget-webkit-goto-uri))
              (with-current-buffer existing
                (xwidget-webkit-goto-uri (xwidget-webkit-current-session) url))
            (user-error "xwidget-webkit-goto-uri is not available"))
          (my/xwidget--record-buffer existing id url)
          (my/xwidget--display-buffer existing display)
          ;; Page already loaded — no load-finished will fire; schedule focus.
          (when (my/xwidget--auto-focus-allowed-p existing)
            (run-at-time 0.3 nil #'my/xwidget-focus existing))
          existing)
      (let ((buffer
             (if (eq display 'side)
                 (my/open--with-browser-window
                  'xwidget-webkit-mode reuse-selected
                  (lambda ()
                    (xwidget-webkit-browse-url url t)
                    (current-buffer)))
               (xwidget-webkit-browse-url url t)
               (current-buffer))))
        (my/xwidget--record-buffer buffer id url)
        (my/xwidget--display-buffer buffer display)
        buffer))))

(defun my/xwidget-open-url-current (url)
  "Open URL in xwidget using the selected window."
  (interactive (browse-url-interactive-arg "xwidget URL: "))
  (my/xwidget-open-url url :display 'current :reuse-selected t))

(defun my/xwidget-reload ()
  "Reload the current xwidget page through the customized API."
  (interactive)
  (if (fboundp 'xwidget-webkit-reload)
      (call-interactively #'xwidget-webkit-reload)
    (user-error "xwidget reload is not available")))

(defun my/xwidget-back ()
  "Navigate the current xwidget page backward."
  (interactive)
  (if (fboundp 'xwidget-webkit-back)
      (call-interactively #'xwidget-webkit-back)
    (user-error "xwidget back is not available")))

(defun my/xwidget-forward ()
  "Navigate the current xwidget page forward."
  (interactive)
  (if (fboundp 'xwidget-webkit-forward)
      (call-interactively #'xwidget-webkit-forward)
    (user-error "xwidget forward is not available")))

(defun my/xwidget-copy-selection ()
  "Copy selection from the current xwidget page."
  (interactive)
  (if (fboundp 'xwidget-webkit-copy-selection-as-kill)
      (call-interactively #'xwidget-webkit-copy-selection-as-kill)
    (user-error "xwidget copy selection is not available")))

(defun my/xwidget-copy-url ()
  "Copy current xwidget URL."
  (interactive)
  (if-let* ((url (my/xwidget-current-url)))
      (progn
        (kill-new url)
        (message "Copied URL."))
    (user-error "No xwidget URL available")))

(defun my/xwidget-open-task-manager ()
  "Open the current Noema page's Core task manager without polling."
  (interactive)
  (my/xwidget--execute-script
   "(() => { if (typeof window.aaronnoteOpenTaskManager === 'function') { window.aaronnoteOpenTaskManager(); return true; } return false; })()"))

(defun my/xwidget--execute-script (script)
  "Execute JavaScript SCRIPT in the current xwidget session."
  (unless (and (fboundp 'xwidget-webkit-current-session)
               (fboundp 'xwidget-webkit-execute-script))
    (user-error "xwidget script execution is not available"))
  (let ((session (xwidget-webkit-current-session)))
    (unless session
      (user-error "No current xwidget session"))
    (xwidget-webkit-execute-script session script)))

(defun my/xwidget--keyboard-command-script (key code modifiers fallback-command)
  "Return JavaScript that dispatches a keyboard command with FALLBACK-COMMAND."
  (format
   "(() => {
  const target = document.activeElement
    || document.querySelector('.cm-content, [contenteditable=\"true\"], textarea, input')
    || document.body;
  const event = new KeyboardEvent('keydown', {
    key: %S,
    code: %S,
    metaKey: %s,
    ctrlKey: %s,
    altKey: %s,
    shiftKey: %s,
    bubbles: true,
    cancelable: true
  });
  const handled = !target.dispatchEvent(event) || event.defaultPrevented;
  if (!handled && document.queryCommandSupported && document.queryCommandSupported(%S)) {
    document.execCommand(%S);
  }
  return true;
})()"
   key
   code
   (if (plist-get modifiers :meta) "true" "false")
   (if (plist-get modifiers :ctrl) "true" "false")
   (if (plist-get modifiers :alt) "true" "false")
   (if (plist-get modifiers :shift) "true" "false")
   fallback-command
   fallback-command))

(defun my/xwidget-undo ()
  "Run undo in the current xwidget page."
  (interactive)
  (my/xwidget--execute-script
   (my/xwidget--keyboard-command-script
    "z" "KeyZ" '(:meta t) "undo")))

(defun my/xwidget-redo ()
  "Run redo in the current xwidget page."
  (interactive)
  (my/xwidget--execute-script
   (my/xwidget--keyboard-command-script
    "Z" "KeyZ" '(:meta t :shift t) "redo")))

(defun my/xwidget-keep-emacs-prefix-keys (map)
  "Remove xwidget bindings that should remain normal Emacs keys in MAP."
  (dolist (key '("M-x" "C-x C-f" "C-x" "C-c" "C-s" "C-g" "M-w" "M-q"))
    (define-key map (kbd key) nil)))

(defun my/xwidget-pass-editing-keys (map)
  "Send editing/navigation keys in MAP to WebKit instead of Emacs."
  (when (fboundp 'xwidget-webkit-pass-command-event)
    (dolist (key '("<escape>"
                   "<delete>"
                   "<backspace>"
                   "DEL"
                   "RET"
                   "<return>"
                   "TAB"
                   "<tab>"
                   "<backtab>"
                   "<iso-lefttab>"
                   "S-TAB"
                   "S-<tab>"
                   "<left>"
                   "<right>"
                   "<up>"
                   "<down>"
                   "<home>"
                   "<end>"
                   "<prior>"
                   "<next>"
                   ;; macOS: Cmd = Meta; pass clipboard shortcuts to WebKit
                   "M-c"
                   "M-v"))
      (define-key map (kbd key) #'xwidget-webkit-pass-command-event))))

(defun my/xwidget-pass-pointer-keys (map)
  "Send pointer wheel events in MAP to WebKit instead of Emacs scrolling."
  (when (fboundp 'xwidget-webkit-pass-command-event)
    (dolist (key '([wheel-up]
                   [wheel-down]
                   [wheel-left]
                   [wheel-right]
                   [double-wheel-up]
                   [double-wheel-down]
                   [double-wheel-left]
                   [double-wheel-right]
                   [triple-wheel-up]
                   [triple-wheel-down]
                   [triple-wheel-left]
                   [triple-wheel-right]
                   [mouse-4]
                   [mouse-5]))
      (define-key map key #'xwidget-webkit-pass-command-event))))

(defun my/xwidget--split-to-ibuffer (split-fn)
  "Run SPLIT-FN, select the new window, and show `ibuffer'."
  (let ((window (funcall split-fn)))
    (select-window window)
    (ibuffer)))

(defun my/xwidget-split-window-below-ibuffer ()
  "Split below from xwidget and show `ibuffer' in the new window."
  (interactive)
  (my/xwidget--split-to-ibuffer #'split-window-below))

(defun my/xwidget-split-window-right-ibuffer ()
  "Split right from xwidget and show `ibuffer' in the new window."
  (interactive)
  (my/xwidget--split-to-ibuffer #'split-window-right))

;; 共享 Brave 的所有数据（需要关闭 Brave）
(config-defvar xwidget-webkit-cookie-file nil
  "Cookie database used by xwidget-webkit."
  :type 'file
  :group 'xwidget)

(config-defvar xwidget-webkit-cache-directory nil
  "Cache directory used by xwidget-webkit."
  :type 'directory
  :group 'xwidget)

(config-defvar xwidget-webkit-local-storage-directory nil
  "Local storage directory used by xwidget-webkit."
  :type 'directory
  :group 'xwidget)

;; === 其他有用的设置 ===
;; 启用 JavaScript
(config-defvar xwidget-webkit-enable-javascript nil
  "Enable JavaScript in xwidget-webkit."
  :type 'boolean
  :group 'xwidget)

;; 启用插件（如 Flash，虽然现在基本不用了）
(config-defvar xwidget-webkit-enable-plugins nil
  "Enable plugins in xwidget-webkit."
  :type 'boolean
  :group 'xwidget)

;; 启用媒体播放
(config-defvar xwidget-webkit-enable-media nil
  "Enable media playback in xwidget-webkit."
  :type 'boolean
  :group 'xwidget)

;; 设置用户代理（伪装成常规浏览器）
(config-defvar xwidget-webkit-user-agent nil
  "User agent string sent by xwidget-webkit."
  :type 'string
  :group 'xwidget)

;; 启用开发者工具
(config-defvar xwidget-webkit-enable-developer-extras nil
  "Enable developer extras in xwidget-webkit."
  :type 'boolean
  :group 'xwidget)

(config-defvar xwidget-webkit-buffer-name-format nil
  "Buffer name format used by xwidget-webkit."
  :type 'string
  :group 'xwidget)

(config-defvar browse-url-browser-function nil
  "Default browser dispatcher for `browse-url'."
  :type 'function
  :group 'browser)

(config-defvar eww-search-prefix nil
  "Search URL prefix used by EWW."
  :type 'string
  :group 'browser)

;;;; xwidget line controls

(defun my/xwidget--mode-line-icon (kind icon fallback)
  "Return nerd ICON of KIND for the xwidget mode line, or FALLBACK."
  (if (and (display-graphic-p)
           (pcase kind
             ('codicon (fboundp 'nerd-icons-codicon))
             (_ (fboundp 'nerd-icons-mdicon))))
      (condition-case nil
          (pcase kind
            ('codicon (nerd-icons-codicon icon :height 0.95))
            (_ (nerd-icons-mdicon icon :height 0.95)))
        (error fallback))
    fallback))

(defun my/xwidget--select-event-window (event)
  "Select the window associated with mouse EVENT when possible."
  (when-let* ((start (event-start event))
              (window (posn-window start)))
    (when (and (windowp window)
               (window-live-p window))
      (select-window window))))

(defun my/xwidget--nav-button (label action help &optional area)
  "Return a propertized line button for LABEL, ACTION, and HELP.
AREA is `mode-line' by default; pass `header-line' for header buttons."
  (let ((map (make-sparse-keymap)))
    (define-key map (vector (or area 'mode-line) 'mouse-1)
      (lambda (event)
        (interactive "e")
        (my/xwidget--select-event-window event)
        (if (commandp action)
            (call-interactively action)
          (funcall action))))
    (propertize (concat " " label " ")
                'mouse-face 'mode-line-highlight
                'help-echo help
                'local-map map)))

(defun my/xwidget--window-menu-item (label command)
  "Return an easy-menu item for LABEL and COMMAND."
  (vector label command (fboundp command)))

(defvar my/xwidget-window-menu-extra-sections nil
  "Functions returning extra top-level items for `my/xwidget-window-menu'.")

(defun my/xwidget-window-menu (event)
  "Show the xwidget window-management popup menu for EVENT."
  (interactive "e")
  (my/xwidget--select-event-window event)
  (popup-menu
   (easy-menu-create-menu
    "Xwidget"
    (append
     (list
     (list
      "Page"
      (my/xwidget--window-menu-item "Open URL here" #'my/xwidget-open-url-current)
      (my/xwidget--window-menu-item "Copy URL" #'my/xwidget-copy-url)
      (my/xwidget--window-menu-item "Copy selection" #'my/xwidget-copy-selection)
      "---"
      (my/xwidget--window-menu-item "Back" #'my/xwidget-back)
      (my/xwidget--window-menu-item "Forward" #'my/xwidget-forward)
      (my/xwidget--window-menu-item "Reload" #'my/xwidget-reload)
      (my/xwidget--window-menu-item "Focus editor" #'my/xwidget-focus)
      "---"
      (my/xwidget--window-menu-item "Undo" #'my/xwidget-undo)
      (my/xwidget--window-menu-item "Redo" #'my/xwidget-redo))
     (list
      "Window"
      (my/xwidget--window-menu-item "Switch buffer" #'switch-to-buffer)
      (my/xwidget--window-menu-item "Buffer list" #'ibuffer)
      (my/xwidget--window-menu-item "Delete window" #'delete-window)
      (my/xwidget--window-menu-item "Toggle one window" #'toggle-one-window)
      "---"
      (my/xwidget--window-menu-item
       "Split below -> ibuffer"
       #'my/xwidget-split-window-below-ibuffer)
      (my/xwidget--window-menu-item
       "Split right -> ibuffer"
       #'my/xwidget-split-window-right-ibuffer)))
     (apply #'append
            (delq nil
                  (mapcar (lambda (fn)
                            (when (functionp fn)
                              (funcall fn)))
                          my/xwidget-window-menu-extra-sections)))))
   event))

(defun my/xwidget--header-browser-buttons ()
  "Return xwidget header-line buttons for browser controls."
  (list
   (my/xwidget--nav-button
    (my/xwidget--mode-line-icon 'codicon "nf-cod-arrow_left" "back")
    #'my/xwidget-back
    "Back [b]"
    'header-line)
   (my/xwidget--nav-button
    (my/xwidget--mode-line-icon 'codicon "nf-cod-arrow_right" "fwd")
    #'my/xwidget-forward
    "Forward [f]"
    'header-line)
   (my/xwidget--nav-button
    (my/xwidget--mode-line-icon 'codicon "nf-cod-refresh" "reload")
    #'my/xwidget-reload
    "Reload [g]"
    'header-line)
   (my/xwidget--nav-button
    (my/xwidget--mode-line-icon 'codicon "nf-cod-edit" "focus")
    #'my/xwidget-focus
    "Focus editor [i]"
    'header-line)
   (my/xwidget--nav-button
    (my/xwidget--mode-line-icon 'codicon "nf-cod-layout" "win")
    #'my/xwidget-window-menu
    "Window menu"
    'header-line)))

(defun my/xwidget-setup-control-line ()
  "Install browser controls and a window popup in this xwidget header line."
  (setq-local header-line-format
              `(" "
                ,@(my/xwidget--header-browser-buttons)
                "  "
                (:eval (propertize (or (my/xwidget-current-url) "")
                                   'face 'shadow))))
  (kill-local-variable 'mode-line-format))

(defalias 'my/xwidget-setup-header-line #'my/xwidget-setup-control-line)

;;;; xwidget-webkit 基础配置（macOS / emacs-plus with-xwidgets）

(defvar my/xwidget--callback-advice-installed nil
  "Non-nil when xwidget callback advice has been installed.")

(when (featurep 'xwidget-internal)
  ;; Keep this free of %-escapes: supported xwidget format keys vary across
  ;; Emacs builds, and unsupported keys raise `format-spec' errors.

  ;; 进入 xwidget buffer 时给常用键（不会污染全局）
  (with-eval-after-load 'xwidget
    (my/xwidget-keep-emacs-prefix-keys xwidget-webkit-mode-map)
    (my/xwidget-keep-emacs-prefix-keys xwidget-webkit-edit-mode-map)
    (my/xwidget-pass-editing-keys xwidget-webkit-mode-map)
    (my/xwidget-pass-editing-keys xwidget-webkit-edit-mode-map)
    (my/xwidget-pass-pointer-keys xwidget-webkit-mode-map)
    (my/xwidget-pass-pointer-keys xwidget-webkit-edit-mode-map)
    (define-key xwidget-webkit-mode-map [remap split-window-below] #'my/xwidget-split-window-below-ibuffer)
    (define-key xwidget-webkit-mode-map [remap split-window-right] #'my/xwidget-split-window-right-ibuffer)
    (define-key xwidget-webkit-mode-map (kbd "q") #'quit-window)
    (define-key xwidget-webkit-mode-map (kbd "g") #'my/xwidget-reload)
    (define-key xwidget-webkit-mode-map (kbd "M-r") #'my/refresh-current-content)
    (define-key xwidget-webkit-mode-map (kbd "l") #'my/xwidget-open-url-current)
    (define-key xwidget-webkit-mode-map (kbd "b") #'my/xwidget-back)
    (define-key xwidget-webkit-mode-map (kbd "f") #'my/xwidget-forward)
    (define-key xwidget-webkit-mode-map (kbd "y") #'my/xwidget-copy-selection)
    (define-key xwidget-webkit-mode-map (kbd "Y") #'my/xwidget-copy-url)
    (define-key xwidget-webkit-mode-map (kbd "i") #'my/xwidget-focus)
    ;; Drive auto-focus and title sync from WebKit callback events.
    (unless my/xwidget--callback-advice-installed
      (advice-add 'xwidget-webkit-callback :after #'my/xwidget--load-finished-focus)
      (advice-add 'xwidget-webkit-callback :after #'my/xwidget--callback-update-buffer-name)
      (setq my/xwidget--callback-advice-installed t))))

;;;; browse-url 统一入口：默认策略由 init-open.el 维护

(defun my/browse-url (url &optional _new-window)
  "Open URL with the central URL route."
  (interactive (browse-url-interactive-arg "URL: "))
  (my/open-url url))

(general-define-key
 :keymaps 'global
 "C-c w e" #'my/open-eww-url
 "C-c w x" #'my/xwidget-open-url
 "C-c w a" #'my/appine-open-url
 "C-c w f" #'my/appine-open-file
 "C-c w g" #'my/appine-open-at-point
 "C-c w h" #'my/appine-back
 "C-c w l" #'my/appine-forward
 "C-c w [" #'my/appine-prev-tab
 "C-c w ]" #'my/appine-next-tab
 "C-c w 0" #'my/appine-close-tab
 "C-c w d" #'my/browser-close-current
 "C-c w ?" #'my/appine-board
 "C-c w w" #'browse-url
 "C-c w s" #'my/browser-switch-to
 "C-c w E" #'my/browser-switch-to-eww
 "C-c w X" #'my/browser-switch-to-xwidget
 "C-c w A" #'my/browser-switch-to-appine
 "C-c w O" #'my/browser-switch-to-open
 "C-c w k" #'my/appine-kill-all)


(with-eval-after-load 'eww
  (define-key eww-mode-map (kbd "g") #'my/refresh-current-content)
  (define-key eww-mode-map (kbd "M-r") #'my/refresh-current-content)
  (define-key eww-mode-map (kbd "M-w") #'delete-window)
  (define-key eww-mode-map (kbd "R") #'eww-readable)
  (define-key eww-mode-map (kbd "X") #'my/eww-to-xwidget)
  (define-key eww-mode-map (kbd "A") #'my/eww-to-appine))
;;; init-base.el ends here

;;; eww <-> xwidget-webkit 互转 (稳健版)

;; ---------- 1. 获取 URL 的工具函数 ----------

(defun my/eww-get-url ()
  "获取当前 EWW buffer 的 URL，带空值检查"
  (if (derived-mode-p 'eww-mode)
      (plist-get eww-data :url)
    nil))

(defun my/xwidget-get-url ()
  "获取当前 Xwidget buffer 的 URL，带空值检查"
  (if (eq major-mode 'xwidget-webkit-mode)
      (my/xwidget-current-url)
    nil))

(defun my/browser-build-search-url (search-term engine)
  "Return a search URL for SEARCH-TERM on ENGINE."
  (require 'url-util)
  (let ((encoded-query (url-hexify-string search-term)))
    (pcase engine
      ('bing (format "https://www.bing.com/search?q=%s" encoded-query))
      ('perplexity (format "https://www.perplexity.ai/search?q=%s" encoded-query))
      ('duckduckgo (format "https://duckduckgo.com/?q=%s" encoded-query))
      (_ (format "https://www.bing.com/search?q=%s" encoded-query)))))

(defun my/browser-current-backend ()
  "Return the current browser backend symbol, or nil."
  (cond
   ((derived-mode-p 'eww-mode) 'eww)
   ((eq major-mode 'xwidget-webkit-mode) 'xwidget)
   ((and (fboundp 'my/appine-get-url)
         (ignore-errors (my/appine-get-url)))
    'appine)
   (t nil)))

(defun my/browser-current-url ()
  "Return the current page URL for the active browser backend."
  (pcase (my/browser-current-backend)
    ('eww (my/eww-get-url))
    ('xwidget (my/xwidget-get-url))
    ('appine (and (fboundp 'my/appine-get-url)
                  (my/appine-get-url)))
    (_ nil)))

(defun my/browser--kill-buffer-and-window ()
  "Kill the current browser buffer and delete its window when possible."
  (let ((buffer (current-buffer))
        (window (selected-window)))
    (let ((kill-buffer-query-functions nil))
      (when (buffer-live-p buffer)
        (kill-buffer buffer)))
    (when (and (window-live-p window)
               (> (length (window-list nil 'no-minibuf)) 1))
      (delete-window window))))

(defun my/browser-close-current ()
  "Close the current browser view or tab.
For EWW and xwidget-webkit, this kills the browser buffer and deletes its
window, avoiding orphan browser buffers/windows."
  (interactive)
  (pcase (my/browser-current-backend)
    ('appine
     (if (fboundp 'my/appine-close-tab)
         (my/appine-close-tab)
       (user-error "Appine close command is not available")))
    ('eww
     (my/browser--kill-buffer-and-window))
    ('xwidget
     (my/browser--kill-buffer-and-window))
    (_
     (user-error "当前 buffer 不是受支持的浏览后端"))))

(defun my/browser-open-url-with-backend (backend url &optional reuse-selected)
  "Open URL with browser BACKEND."
  (my/open-url-with-backend url backend reuse-selected))

(defun my/browser-cleanup-backend (backend buffer)
  "Clean up BACKEND using BUFFER after a successful switch."
  (pcase backend
    ('appine
     (when (fboundp 'my/appine-kill-all)
       (my/appine-kill-all)))
    (_
     (when (buffer-live-p buffer)
       (kill-buffer buffer)))))

(defun my/refresh-current-content ()
  "Refresh the current web view or file buffer."
  (interactive)
  (cond
   ((eq (my/browser-current-backend) 'appine)
    (call-interactively #'my/appine-reload))
   ((derived-mode-p 'eww-mode)
    (call-interactively #'eww-reload))
   ((eq major-mode 'xwidget-webkit-mode)
    (call-interactively #'my/xwidget-reload))
   ((or (buffer-file-name) (derived-mode-p 'dired-mode))
    (if (buffer-modified-p)
        (user-error "当前 buffer 有未保存修改，先保存再刷新")
      (revert-buffer :ignore-auto :noconfirm :preserve-modes)
      (message "已刷新: %s" (buffer-name))))
   (t
    (user-error "当前 buffer 不支持刷新"))))

(general-define-key
 :keymaps 'global
 "C-c w r" #'my/refresh-current-content)

(defun my/browser-switch-to (backend)
  "Switch the current browser page to BACKEND."
  (interactive
   (list (my/open-read-backend 'url "Switch browser to: ")))
  (let ((backend (my/open-normalize-backend backend))
        (source-backend (my/browser-current-backend))
        (url (my/browser-current-url))
        (old-buf (current-buffer)))
    (unless source-backend
      (user-error "当前 buffer 不是受支持的浏览后端"))
    (unless url
      (user-error "无法获取当前页面 URL"))
    (when (eq source-backend backend)
      (user-error "当前已经是 %s" backend))
    (message "正在切换至 %s: %s" backend url)
    (my/browser-open-url-with-backend backend url t)
    (run-at-time "0 sec" nil #'my/browser-cleanup-backend source-backend old-buf)))

(defun my/browser-switch-to-eww ()
  "Switch the current browser page to EWW."
  (interactive)
  (my/browser-switch-to 'eww))

(defun my/browser-switch-to-xwidget ()
  "Switch the current browser page to xwidget-webkit."
  (interactive)
  (my/browser-switch-to 'xwidget))

(defun my/browser-switch-to-appine ()
  "Switch the current browser page to Appine."
  (interactive)
  (my/browser-switch-to 'appine))

(defun my/browser-switch-to-open ()
  "Open the current browser page with macOS open."
  (interactive)
  (my/browser-switch-to 'system))

(defun my/eww-to-appine ()
  "Switch the current EWW page to Appine."
  (interactive)
  (my/browser-switch-to 'appine))

(defun my/xwidget-to-appine ()
  "Switch the current xwidget page to Appine."
  (interactive)
  (my/browser-switch-to 'appine))

(defun my/appine-to-eww ()
  "Switch the current Appine page to EWW."
  (interactive)
  (my/browser-switch-to 'eww))

(defun my/appine-to-xwidget ()
  "Switch the current Appine page to xwidget-webkit."
  (interactive)
  (my/browser-switch-to 'xwidget))

;; ---------- 2. 核心切换逻辑 (带延迟清理) ----------

(defun my/eww-to-xwidget ()
  "从 EWW 切换到 Xwidget，成功后延迟清理旧 Buffer"
  (interactive)
  (let ((url (my/eww-get-url))
        (old-buf (current-buffer)))
    (if url
        (progn
          (message "正在切换至 Xwidget: %s" url)
          ;; 启动 xwidget
          (my/xwidget-open-url url :display 'current :reuse-selected t)
          ;; 【关键修正】：不要立即杀 buffer。
          ;; 使用 run-at-time 0 让 Emacs 先完成 buffer 切换和界面重绘，
          ;; 待事件循环空闲时再回头杀掉旧 buffer。
          (run-at-time "0 sec" nil 
                       (lambda (b) 
                         (when (buffer-live-p b)
                           (kill-buffer b))) 
                       old-buf))
      (message "错误：无法获取 EWW URL"))))

(defun my/xwidget-to-eww ()
  "从 Xwidget 切换到 EWW，成功后延迟清理旧 Buffer"
  (interactive)
  (let ((url (my/xwidget-get-url))
        (old-buf (current-buffer)))
    (if url
        (progn
          (message "正在切换至 EWW: %s" url)
          ;; 启动 eww
          (my/open-eww-url url t)
          ;; 【关键修正】：同样延迟清理，防止 xwidget 还没隐藏就被杀掉导致闪退
          (run-at-time "0 sec" nil 
                       (lambda (b) 
                         (when (buffer-live-p b)
                           (kill-buffer b))) 
                       old-buf))
      (message "错误：无法获取 Xwidget URL"))))


(defun my/browser-open-search (search-term &optional engine browser)
  "Search SEARCH-TERM with selected search ENGINE and BROWSER."
  (interactive
   (list
    (read-string "Search: ")
     (intern (completing-read "Search Engine (default: bing): "
                            '("bing" "perplexity" "duckduckgo")
                            nil t nil nil "bing"))
     (my/open-read-backend 'search "Browser: ")))
  (my/browser-open-url-with-backend
   (or browser (my/open-resolve-backend 'search))
   (my/browser-build-search-url search-term engine)))

(with-eval-after-load 'xwidget
  (define-key xwidget-webkit-mode-map (kbd "M-w") #'my/browser-close-current)
  (define-key xwidget-webkit-edit-mode-map (kbd "M-w") #'my/browser-close-current)
  (define-key xwidget-webkit-mode-map (kbd "W") #'my/xwidget-to-eww)
  (define-key xwidget-webkit-mode-map (kbd "A") #'my/xwidget-to-appine)
  (add-hook 'xwidget-webkit-mode-hook #'my/xwidget-setup-control-line))




(provide 'init-browser)
