;;; init-patches.el --- Temporary third-party compatibility patches -*- lexical-binding: t; -*-

;;; Commentary:
;; Keep workarounds for package/Emacs version skew here.  Each patch should be
;; removed when its upstream package or the minimum supported Emacs fixes it.

;;; Code:

;; Package bytecode produced by newer Emacs 31 snapshots may call this helper,
;; while snapshots from before the derived-type dispatch change do not provide
;; it.  Register the two properties understood by the older `cl-lib' runtime;
;; package types using the newer bytecode can then load normally.  PARENTS is
;; metadata for the newer dispatch implementation and has no equivalent here.
(defun my/patch-cl--define-derived-type
    (name expander predicate &optional _parents)
  "Register a newer-bytecode derived type on an older `cl-lib' runtime."
  (define-symbol-prop name 'cl-deftype-handler expander)
  (when predicate
    (define-symbol-prop name 'cl-deftype-satisfies predicate)))

(unless (fboundp 'cl--define-derived-type)
  (defalias 'cl--define-derived-type #'my/patch-cl--define-derived-type))

;; Recent `easy-mmode' versions keep a buffer registry for globalized minor
;; modes.  Package autoloads/bytecode generated by a different Emacs snapshot
;; can install the new enable-in-buffer function without emitting its matching
;; `defvar'.  Predeclare the registries used by affected third-party packages
;; so changing major mode (notably when Noema creates an xwidget buffer) cannot
;; signal a void-variable error during mixed-version startup.
(defvar global-atomic-chrome-edit-mode-buffers nil
  "Buffers managed by `global-atomic-chrome-edit-mode'.")

(defvar better-jumper-mode-buffers nil
  "Buffers managed by `better-jumper-mode'.")

(defvar-local better-jumper-local-mode-set-explicitly nil
  "Non-nil when `better-jumper-local-mode' was toggled explicitly.")

(defvar-local better-jumper-local-mode--set-explicitly nil
  "Newer spelling of the explicit `better-jumper-local-mode' toggle flag.")

(defvar better-jumper-local-mode--suppress-set-explicitly nil
  "Non-nil while the global Better Jumper mode toggles its local mode.")

;; `diff-hl' is affected by the same `easy-mmode' ABI transition.  Its
;; packaged bytecode and native cache can use different spellings while the
;; global mode enables `diff-hl-mode' as a file (including Markdown) opens.
(defvar global-diff-hl-mode-buffers nil
  "Buffers managed by `global-diff-hl-mode'.")

(defvar-local diff-hl-mode-set-explicitly nil
  "Legacy spelling of the explicit `diff-hl-mode' toggle flag.")

(defvar-local diff-hl-mode--set-explicitly nil
  "Current spelling of the explicit `diff-hl-mode' toggle flag.")

(defvar diff-hl-mode--suppress-set-explicitly nil
  "Non-nil while global Diff-HL toggles its local mode.")

;; Jupyter's optional `/jpy:' handler uses the old TRAMP predicate contract.
(defun my/patch-tramp-register-foreign-file-name-handler-a
    (orig-fn function handler &optional append)
  "Skip the incompatible Jupyter foreign TRAMP HANDLER."
  (if (or (eq function 'jupyter-tramp-file-name-p)
          (eq handler 'jupyter-tramp-file-name-handler))
      nil
    (funcall orig-fn function handler append)))

(advice-add 'tramp-register-foreign-file-name-handler
            :around #'my/patch-tramp-register-foreign-file-name-handler-a)

(with-eval-after-load 'jupyter-tramp
  (setq tramp-foreign-file-name-handler-alist
        (assq-delete-all 'jupyter-tramp-file-name-p
                         tramp-foreign-file-name-handler-alist)))

;; The installed tramp-rpc package requires a newer Tramp than Emacs provides.
(defun my/patch-tramp-rpc-available-p ()
  "Return non-nil when the installed tramp-rpc can load on this Emacs."
  (and (boundp 'tramp-version)
       (version-list-<= (version-to-list "2.8.1.4")
                        (version-to-list tramp-version))))

;; Older Magit bytecode installs an `incf'-based auto-revert advice.
(with-eval-after-load 'magit-autorevert
  (when (advice-member-p 'auto-revert-buffers@buffer-list-filter
                         'auto-revert-buffers)
    (advice-remove 'auto-revert-buffers
                   'auto-revert-buffers@buffer-list-filter)))

;; Project API variables are not defined by all supported Emacs releases.
(defvar project-list-exclude nil)

;; `defvar-local' requires an explicit initial value on the older runtime.
(defvar-local my/noema-buffer-file-name nil)

(provide 'patches/init-patches)
;;; init-patches.el ends here
